name: common_tools
description: "Private reusable Flutter design system, components, and application tools."
version: 0.1.0
homepage: https://github.com/Lucifer1091/common_tools
repository: https://github.com/Lucifer1091/common_tools
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:

  #--- UI packages ---#
  cross_file: ^0.3.5+4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.3.0
  flutter_slidable: ^4.0.3
  lucide_icons_flutter: ^3.1.15
  
  #--- Logic packages ---#
  intl: ^0.20.2

  #--- Http packages ---#
  dio: ^5.11.0
  url_launcher: ^6.3.2

  #--- Hardware packages ---#
  local_auth: ^3.0.2
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  mime: ^2.0.0
  path: ^1.9.1

  #--- Misc packages ---#
  logger: ^2.6.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true

  fonts:
    - family: Geist
      fonts:
        - asset: lib/fonts/geist/Geist-Thin.otf
          weight: 100
        - asset: lib/fonts/geist/Geist-ThinItalic.otf
          weight: 100
          style: italic
        - asset: lib/fonts/geist/Geist-ExtraLight.otf
          weight: 200
        - asset: lib/fonts/geist/Geist-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: lib/fonts/geist/Geist-Light.otf
          weight: 300
        - asset: lib/fonts/geist/Geist-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/fonts/geist/Geist-Regular.otf
          weight: 400
        - asset: lib/fonts/geist/Geist-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/fonts/geist/Geist-Medium.otf
          weight: 500
        - asset: lib/fonts/geist/Geist-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/fonts/geist/Geist-SemiBold.otf
          weight: 600
        - asset: lib/fonts/geist/Geist-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: lib/fonts/geist/Geist-Bold.otf
          weight: 700
        - asset: lib/fonts/geist/Geist-BoldItalic.otf
          weight: 700
          style: italic
        - asset: lib/fonts/geist/Geist-ExtraBold.otf
          weight: 800
        - asset: lib/fonts/geist/Geist-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: lib/fonts/geist/Geist-Black.otf
          weight: 900
        - asset: lib/fonts/geist/Geist-BlackItalic.otf
          weight: 900
          style: italic

    - family: GeistMono
      fonts:
        - asset: lib/fonts/geist_mono/GeistMono-Thin.otf
          weight: 100
        - asset: lib/fonts/geist_mono/GeistMono-ThinItalic.otf
          weight: 100
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-ExtraLight.otf
          weight: 200
        - asset: lib/fonts/geist_mono/GeistMono-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-Light.otf
          weight: 300
        - asset: lib/fonts/geist_mono/GeistMono-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-Regular.otf
          weight: 400
        - asset: lib/fonts/geist_mono/GeistMono-Italic.otf
          weight: 400
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-Medium.otf
          weight: 500
        - asset: lib/fonts/geist_mono/GeistMono-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-SemiBold.otf
          weight: 600
        - asset: lib/fonts/geist_mono/GeistMono-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-Bold.otf
          weight: 700
        - asset: lib/fonts/geist_mono/GeistMono-BoldItalic.otf
          weight: 700
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-ExtraBold.otf
          weight: 800
        - asset: lib/fonts/geist_mono/GeistMono-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: lib/fonts/geist_mono/GeistMono-Black.otf
          weight: 900
        - asset: lib/fonts/geist_mono/GeistMono-BlackItalic.otf
          weight: 900
          style: italic
