name: common_tools
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Lucifer1091/common_tools

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  #--- UI packages ---#
  pinput: ^5.0.2
  dotted_border: ^3.1.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_svg: ^2.2.1
  easy_refresh: ^3.4.0
  flutter_slidable: ^4.0.1
  lucide_icons_flutter: ^3.1.1
  
  #--- Form packages ---#
  form_field_validator: ^1.1.0
  flutter_form_builder: ^10.2.0

  #--- Logic packages ---#
  intl: ^0.20.2
  encrypt: ^5.0.3

  #--- Http packages ---#
  dio: ^5.9.0
  url_launcher: ^6.3.2

  #--- Hardware packages ---#
  local_auth: ^2.3.0 # biometric authentication
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  mime: ^2.0.0
  mobile_scanner: ^7.0.1
  path: ^1.9.1

  #--- Misc packages ---#
  logger: ^2.6.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

fonts:
  - family: Geist
    fonts:
      - asset: fonts/geist/Geist-Thin.otf
        weight: 100
      - asset: fonts/geist/Geist-UltraLight.otf
        weight: 200
      - asset: fonts/geist/Geist-Light.otf
        weight: 300
      - asset: fonts/geist/Geist-Regular.otf
        weight: 400
      - asset: fonts/geist/Geist-Medium.otf
        weight: 500
      - asset: fonts/geist/Geist-SemiBold.otf
        weight: 600
      - asset: fonts/geist/Geist-Bold.otf
        weight: 700
      - asset: fonts/geist/Geist-Black.otf
        weight: 800
      - asset: fonts/geist/Geist-UltraBlack.otf
        weight: 900

  - family: GeistMono
    fonts:
      - asset: fonts/geist_mono/GeistMono-Thin.otf
        weight: 100
      - asset: fonts/geist_mono/GeistMono-UltraLight.otf
        weight: 200
      - asset: fonts/geist_mono/GeistMono-Light.otf
        weight: 300
      - asset: fonts/geist_mono/GeistMono-Regular.otf
        weight: 400
      - asset: fonts/geist_mono/GeistMono-Medium.otf
        weight: 500
      - asset: fonts/geist_mono/GeistMono-SemiBold.otf
        weight: 600
      - asset: fonts/geist_mono/GeistMono-Bold.otf
        weight: 700
      - asset: fonts/geist_mono/GeistMono-Black.otf
        weight: 800
      - asset: fonts/geist_mono/GeistMono-UltraBlack.otf
        weight: 900
