import 'models/models.dart';

class CountryData {
  CountryData._();

  static const List<Country> all = <Country>[
    Country(
      name: "Afghanistan",
      iso2: "AF",
      iso3: "AFG",
      region: "Asia",
      flagEmoji: "🇦🇫",
      dialCode: "+93",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AFN", name: "Afghan afghani", symbol: "؋"),
      ],
      languages: <String>["Pashto", "Dari"],
      timezones: <String>["Asia/Kabul"],
    ),
    Country(
      name: "Aland Islands",
      iso2: "AX",
      iso3: "ALA",
      region: "Europe",
      flagEmoji: "🇦🇽",
      dialCode: "+35818",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Swedish"],
      timezones: <String>["Europe/Mariehamn"],
    ),
    Country(
      name: "Albania",
      iso2: "AL",
      iso3: "ALB",
      region: "Europe",
      flagEmoji: "🇦🇱",
      dialCode: "+355",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ALL", name: "Albanian lek", symbol: "Lek"),
      ],
      languages: <String>["Albanian"],
      timezones: <String>["Europe/Tirane"],
    ),
    Country(
      name: "Algeria",
      iso2: "DZ",
      iso3: "DZA",
      region: "Africa",
      flagEmoji: "🇩🇿",
      dialCode: "+213",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DZD", name: "Algerian dinar", symbol: "دج"),
      ],
      languages: <String>["Arabic", "Berber"],
      timezones: <String>["Africa/Algiers"],
    ),
    Country(
      name: "American Samoa",
      iso2: "AS",
      iso3: "ASM",
      region: "Oceania",
      flagEmoji: "🇦🇸",
      dialCode: "+1684",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "US Dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Samoan"],
      timezones: <String>["Pacific/Pago_Pago"],
    ),
    Country(
      name: "Andorra",
      iso2: "AD",
      iso3: "AND",
      region: "Europe",
      flagEmoji: "🇦🇩",
      dialCode: "+376",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Catalan"],
      timezones: <String>["Europe/Andorra"],
    ),
    Country(
      name: "Angola",
      iso2: "AO",
      iso3: "AGO",
      region: "Africa",
      flagEmoji: "🇦🇴",
      dialCode: "+244",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AOA", name: "Angolan kwanza", symbol: "Kz"),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>["Africa/Luanda"],
    ),
    Country(
      name: "Anguilla",
      iso2: "AI",
      iso3: "AIA",
      region: "Americas",
      flagEmoji: "🇦🇮",
      dialCode: "+1264",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "XCD", name: "East Caribbean dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Anguilla"],
    ),
    Country(
      name: "Antarctica",
      iso2: "AQ",
      iso3: "ATA",
      region: "Polar",
      flagEmoji: "🇦🇶",
      dialCode: "+672",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AAD", name: "Antarctican dollar", symbol: "\$"),
        CurrencyInfo(code: "USD", name: "", symbol: ""),
      ],
      languages: <String>[],
      timezones: <String>[
        "Antarctica/Casey",
        "Antarctica/Davis",
        "Antarctica/DumontDUrville",
        "Antarctica/Mawson",
        "Antarctica/McMurdo",
        "Antarctica/Palmer",
        "Antarctica/Rothera",
        "Antarctica/Syowa",
        "Antarctica/Troll",
        "Antarctica/Vostok",
      ],
    ),
    Country(
      name: "Antigua And Barbuda",
      iso2: "AG",
      iso3: "ATG",
      region: "Americas",
      flagEmoji: "🇦🇬",
      dialCode: "+1268",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Antigua"],
    ),
    Country(
      name: "Argentina",
      iso2: "AR",
      iso3: "ARG",
      region: "Americas",
      flagEmoji: "🇦🇷",
      dialCode: "+54",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ARS", name: "Argentine peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>[
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
      ],
    ),
    Country(
      name: "Armenia",
      iso2: "AM",
      iso3: "ARM",
      region: "Asia",
      flagEmoji: "🇦🇲",
      dialCode: "+374",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AMD", name: "Armenian dram", symbol: "֏"),
      ],
      languages: <String>["Armenian"],
      timezones: <String>["Asia/Yerevan"],
    ),
    Country(
      name: "Aruba",
      iso2: "AW",
      iso3: "ABW",
      region: "Americas",
      flagEmoji: "🇦🇼",
      dialCode: "+297",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AWG", name: "Aruban florin", symbol: "ƒ"),
      ],
      languages: <String>["Dutch", "Papiamento"],
      timezones: <String>["America/Aruba"],
    ),
    Country(
      name: "Australia",
      iso2: "AU",
      iso3: "AUS",
      region: "Oceania",
      flagEmoji: "🇦🇺",
      dialCode: "+61",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>[
        "Antarctica/Macquarie",
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Currie",
        "Australia/Darwin",
        "Australia/Eucla",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/Perth",
        "Australia/Sydney",
      ],
    ),
    Country(
      name: "Austria",
      iso2: "AT",
      iso3: "AUT",
      region: "Europe",
      flagEmoji: "🇦🇹",
      dialCode: "+43",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["German"],
      timezones: <String>["Europe/Vienna"],
    ),
    Country(
      name: "Azerbaijan",
      iso2: "AZ",
      iso3: "AZE",
      region: "Asia",
      flagEmoji: "🇦🇿",
      dialCode: "+994",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AZN", name: "Azerbaijani manat", symbol: "m"),
      ],
      languages: <String>["Azerbaijani"],
      timezones: <String>["Asia/Baku"],
    ),
    Country(
      name: "Bahrain",
      iso2: "BH",
      iso3: "BHR",
      region: "Asia",
      flagEmoji: "🇧🇭",
      dialCode: "+973",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BHD", name: "Bahraini dinar", symbol: ".د.ب"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Bahrain"],
    ),
    Country(
      name: "Bangladesh",
      iso2: "BD",
      iso3: "BGD",
      region: "Asia",
      flagEmoji: "🇧🇩",
      dialCode: "+880",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BDT", name: "Bangladeshi taka", symbol: "৳"),
      ],
      languages: <String>["Bengali"],
      timezones: <String>["Asia/Dhaka"],
    ),
    Country(
      name: "Barbados",
      iso2: "BB",
      iso3: "BRB",
      region: "Americas",
      flagEmoji: "🇧🇧",
      dialCode: "+1246",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BBD", name: "Barbadian dollar", symbol: "Bds\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Barbados"],
    ),
    Country(
      name: "Belarus",
      iso2: "BY",
      iso3: "BLR",
      region: "Europe",
      flagEmoji: "🇧🇾",
      dialCode: "+375",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BYN", name: "Belarusian ruble", symbol: "Br"),
      ],
      languages: <String>["Belarusian", "Russian"],
      timezones: <String>["Europe/Minsk"],
    ),
    Country(
      name: "Belgium",
      iso2: "BE",
      iso3: "BEL",
      region: "Europe",
      flagEmoji: "🇧🇪",
      dialCode: "+32",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Dutch", "French", "German"],
      timezones: <String>["Europe/Brussels"],
    ),
    Country(
      name: "Belize",
      iso2: "BZ",
      iso3: "BLZ",
      region: "Americas",
      flagEmoji: "🇧🇿",
      dialCode: "+501",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BZD", name: "Belize dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Belize"],
    ),
    Country(
      name: "Benin",
      iso2: "BJ",
      iso3: "BEN",
      region: "Africa",
      flagEmoji: "🇧🇯",
      dialCode: "+229",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Porto-Novo"],
    ),
    Country(
      name: "Bermuda",
      iso2: "BM",
      iso3: "BMU",
      region: "Americas",
      flagEmoji: "🇧🇲",
      dialCode: "+1441",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BMD", name: "Bermudian dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Atlantic/Bermuda"],
    ),
    Country(
      name: "Bhutan",
      iso2: "BT",
      iso3: "BTN",
      region: "Asia",
      flagEmoji: "🇧🇹",
      dialCode: "+975",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BTN", name: "Bhutanese ngultrum", symbol: "Nu."),
      ],
      languages: <String>["Dzongkha"],
      timezones: <String>["Asia/Thimphu"],
    ),
    Country(
      name: "Bolivia",
      iso2: "BO",
      iso3: "BOL",
      region: "Americas",
      flagEmoji: "🇧🇴",
      dialCode: "+591",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BOB", name: "Bolivian boliviano", symbol: "Bs."),
      ],
      languages: <String>["Spanish", "Quechua", "Aymara"],
      timezones: <String>["America/La_Paz"],
    ),
    Country(
      name: "Bonaire, Sint Eustatius and Saba",
      iso2: "BQ",
      iso3: "BES",
      region: "Americas",
      flagEmoji: "🇧🇶",
      dialCode: "+599",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["Dutch", "English"],
      timezones: <String>["America/Anguilla"],
    ),
    Country(
      name: "Bosnia and Herzegovina",
      iso2: "BA",
      iso3: "BIH",
      region: "Europe",
      flagEmoji: "🇧🇦",
      dialCode: "+387",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "BAM",
          name: "Bosnia and Herzegovina convertible mark",
          symbol: "KM",
        ),
      ],
      languages: <String>["Bosnian", "Croatian", "Serbian"],
      timezones: <String>["Europe/Sarajevo"],
    ),
    Country(
      name: "Botswana",
      iso2: "BW",
      iso3: "BWA",
      region: "Africa",
      flagEmoji: "🇧🇼",
      dialCode: "+267",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BWP", name: "Botswana pula", symbol: "P"),
      ],
      languages: <String>["English", "Tswana"],
      timezones: <String>["Africa/Gaborone"],
    ),
    Country(
      name: "Bouvet Island",
      iso2: "BV",
      iso3: "BVT",
      region: "Antarctica",
      flagEmoji: "🇧🇻",
      dialCode: "+0055",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NOK", name: "Norwegian Krone", symbol: "kr"),
      ],
      languages: <String>[],
      timezones: <String>["Europe/Oslo"],
    ),
    Country(
      name: "Brazil",
      iso2: "BR",
      iso3: "BRA",
      region: "Americas",
      flagEmoji: "🇧🇷",
      dialCode: "+55",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BRL", name: "Brazilian real", symbol: "R\$"),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>[
        "America/Araguaina",
        "America/Bahia",
        "America/Belem",
        "America/Boa_Vista",
        "America/Campo_Grande",
        "America/Cuiaba",
        "America/Eirunepe",
        "America/Fortaleza",
        "America/Maceio",
        "America/Manaus",
        "America/Noronha",
        "America/Porto_Velho",
        "America/Recife",
        "America/Rio_Branco",
        "America/Santarem",
        "America/Sao_Paulo",
      ],
    ),
    Country(
      name: "British Indian Ocean Territory",
      iso2: "IO",
      iso3: "IOT",
      region: "Africa",
      flagEmoji: "🇮🇴",
      dialCode: "+246",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>[],
      timezones: <String>["Indian/Chagos"],
    ),
    Country(
      name: "Brunei",
      iso2: "BN",
      iso3: "BRN",
      region: "Asia",
      flagEmoji: "🇧🇳",
      dialCode: "+673",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BND", name: "Brunei dollar", symbol: "B\$"),
      ],
      languages: <String>["Malay"],
      timezones: <String>["Asia/Brunei"],
    ),
    Country(
      name: "Bulgaria",
      iso2: "BG",
      iso3: "BGR",
      region: "Europe",
      flagEmoji: "🇧🇬",
      dialCode: "+359",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BGN", name: "Bulgarian lev", symbol: "Лв."),
      ],
      languages: <String>["Bulgarian"],
      timezones: <String>["Europe/Sofia"],
    ),
    Country(
      name: "Burkina Faso",
      iso2: "BF",
      iso3: "BFA",
      region: "Africa",
      flagEmoji: "🇧🇫",
      dialCode: "+226",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Ouagadougou"],
    ),
    Country(
      name: "Burundi",
      iso2: "BI",
      iso3: "BDI",
      region: "Africa",
      flagEmoji: "🇧🇮",
      dialCode: "+257",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BIF", name: "Burundian franc", symbol: "FBu"),
      ],
      languages: <String>["Kirundi", "French"],
      timezones: <String>["Africa/Bujumbura"],
    ),
    Country(
      name: "Cambodia",
      iso2: "KH",
      iso3: "KHM",
      region: "Asia",
      flagEmoji: "🇰🇭",
      dialCode: "+855",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KHR", name: "Cambodian riel", symbol: "KHR"),
      ],
      languages: <String>["Khmer", "Khmer language"],
      timezones: <String>["Asia/Phnom_Penh"],
    ),
    Country(
      name: "Cameroon",
      iso2: "CM",
      iso3: "CMR",
      region: "Africa",
      flagEmoji: "🇨🇲",
      dialCode: "+237",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FCFA",
        ),
      ],
      languages: <String>["French", "English"],
      timezones: <String>["Africa/Douala"],
    ),
    Country(
      name: "Canada",
      iso2: "CA",
      iso3: "CAN",
      region: "Americas",
      flagEmoji: "🇨🇦",
      dialCode: "+1",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CAD", name: "Canadian dollar", symbol: "\$"),
      ],
      languages: <String>["English", "French"],
      timezones: <String>[
        "America/Atikokan",
        "America/Blanc-Sablon",
        "America/Cambridge_Bay",
        "America/Creston",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Edmonton",
        "America/Fort_Nelson",
        "America/Glace_Bay",
        "America/Goose_Bay",
        "America/Halifax",
        "America/Inuvik",
        "America/Iqaluit",
        "America/Moncton",
        "America/Nipigon",
        "America/Pangnirtung",
        "America/Rainy_River",
        "America/Rankin_Inlet",
        "America/Regina",
        "America/Resolute",
        "America/St_Johns",
        "America/Swift_Current",
        "America/Thunder_Bay",
        "America/Toronto",
        "America/Vancouver",
        "America/Whitehorse",
        "America/Winnipeg",
        "America/Yellowknife",
      ],
    ),
    Country(
      name: "Cape Verde",
      iso2: "CV",
      iso3: "CPV",
      region: "Africa",
      flagEmoji: "🇨🇻",
      dialCode: "+238",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CVE", name: "Cape Verdean escudo", symbol: "\$"),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>["Atlantic/Cape_Verde"],
    ),
    Country(
      name: "Cayman Islands",
      iso2: "KY",
      iso3: "CYM",
      region: "Americas",
      flagEmoji: "🇰🇾",
      dialCode: "+1345",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KYD", name: "Cayman Islands dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Cayman"],
    ),
    Country(
      name: "Central African Republic",
      iso2: "CF",
      iso3: "CAF",
      region: "Africa",
      flagEmoji: "🇨🇫",
      dialCode: "+236",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FCFA",
        ),
      ],
      languages: <String>["French", "Sango"],
      timezones: <String>["Africa/Bangui"],
    ),
    Country(
      name: "Chad",
      iso2: "TD",
      iso3: "TCD",
      region: "Africa",
      flagEmoji: "🇹🇩",
      dialCode: "+235",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FCFA",
        ),
      ],
      languages: <String>["French", "Arabic"],
      timezones: <String>["Africa/Ndjamena"],
    ),
    Country(
      name: "Chile",
      iso2: "CL",
      iso3: "CHL",
      region: "Americas",
      flagEmoji: "🇨🇱",
      dialCode: "+56",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CLP", name: "Chilean peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>[
        "America/Punta_Arenas",
        "America/Santiago",
        "Pacific/Easter",
      ],
    ),
    Country(
      name: "China",
      iso2: "CN",
      iso3: "CHN",
      region: "Asia",
      flagEmoji: "🇨🇳",
      dialCode: "+86",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CNY", name: "Chinese yuan", symbol: "¥"),
      ],
      languages: <String>["Mandarin", "Chinese"],
      timezones: <String>["Asia/Shanghai", "Asia/Urumqi"],
    ),
    Country(
      name: "Christmas Island",
      iso2: "CX",
      iso3: "CXR",
      region: "Oceania",
      flagEmoji: "🇨🇽",
      dialCode: "+61",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Chinese (Mandarin)"],
      timezones: <String>["Indian/Christmas"],
    ),
    Country(
      name: "Cocos (Keeling) Islands",
      iso2: "CC",
      iso3: "CCK",
      region: "Oceania",
      flagEmoji: "🇨🇨",
      dialCode: "+61",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Indian/Cocos"],
    ),
    Country(
      name: "Colombia",
      iso2: "CO",
      iso3: "COL",
      region: "Americas",
      flagEmoji: "🇨🇴",
      dialCode: "+57",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "COP", name: "Colombian peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Bogota"],
    ),
    Country(
      name: "Comoros",
      iso2: "KM",
      iso3: "COM",
      region: "Africa",
      flagEmoji: "🇰🇲",
      dialCode: "+269",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KMF", name: "Comorian franc", symbol: "CF"),
      ],
      languages: <String>["Comorian", "Arabic", "French"],
      timezones: <String>["Indian/Comoro"],
    ),
    Country(
      name: "Congo",
      iso2: "CG",
      iso3: "COG",
      region: "Africa",
      flagEmoji: "🇨🇬",
      dialCode: "+242",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FC",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Brazzaville"],
    ),
    Country(
      name: "Cook Islands",
      iso2: "CK",
      iso3: "COK",
      region: "Oceania",
      flagEmoji: "🇨🇰",
      dialCode: "+682",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NZD", name: "Cook Islands dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Cook Islands Māori"],
      timezones: <String>["Pacific/Rarotonga"],
    ),
    Country(
      name: "Costa Rica",
      iso2: "CR",
      iso3: "CRI",
      region: "Americas",
      flagEmoji: "🇨🇷",
      dialCode: "+506",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CRC", name: "Costa Rican colón", symbol: "₡"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Costa_Rica"],
    ),
    Country(
      name: "Cote D'Ivoire (Ivory Coast)",
      iso2: "CI",
      iso3: "CIV",
      region: "Africa",
      flagEmoji: "🇨🇮",
      dialCode: "+225",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Abidjan"],
    ),
    Country(
      name: "Croatia",
      iso2: "HR",
      iso3: "HRV",
      region: "Europe",
      flagEmoji: "🇭🇷",
      dialCode: "+385",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "HRK", name: "Croatian kuna", symbol: "kn"),
        CurrencyInfo(code: "EUR", name: "", symbol: ""),
      ],
      languages: <String>["Croatian"],
      timezones: <String>["Europe/Zagreb"],
    ),
    Country(
      name: "Cuba",
      iso2: "CU",
      iso3: "CUB",
      region: "Americas",
      flagEmoji: "🇨🇺",
      dialCode: "+53",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CUP", name: "Cuban peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Havana"],
    ),
    Country(
      name: "Curaçao",
      iso2: "CW",
      iso3: "CUW",
      region: "Americas",
      flagEmoji: "🇨🇼",
      dialCode: "+599",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "ANG",
          name: "Netherlands Antillean guilder",
          symbol: "ƒ",
        ),
      ],
      languages: <String>["Dutch", "Papiamento"],
      timezones: <String>["America/Curacao"],
    ),
    Country(
      name: "Cyprus",
      iso2: "CY",
      iso3: "CYP",
      region: "Europe",
      flagEmoji: "🇨🇾",
      dialCode: "+357",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Greek", "Turkish"],
      timezones: <String>["Asia/Famagusta", "Asia/Nicosia"],
    ),
    Country(
      name: "Czech Republic",
      iso2: "CZ",
      iso3: "CZE",
      region: "Europe",
      flagEmoji: "🇨🇿",
      dialCode: "+420",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CZK", name: "Czech koruna", symbol: "Kč"),
      ],
      languages: <String>["Czech"],
      timezones: <String>["Europe/Prague"],
    ),
    Country(
      name: "Democratic Republic of the Congo",
      iso2: "CD",
      iso3: "COD",
      region: "Africa",
      flagEmoji: "🇨🇩",
      dialCode: "+243",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CDF", name: "Congolese Franc", symbol: "FC"),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Kinshasa", "Africa/Lubumbashi"],
    ),
    Country(
      name: "Denmark",
      iso2: "DK",
      iso3: "DNK",
      region: "Europe",
      flagEmoji: "🇩🇰",
      dialCode: "+45",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DKK", name: "Danish krone", symbol: "Kr."),
      ],
      languages: <String>["Danish"],
      timezones: <String>["Europe/Copenhagen"],
    ),
    Country(
      name: "Djibouti",
      iso2: "DJ",
      iso3: "DJI",
      region: "Africa",
      flagEmoji: "🇩🇯",
      dialCode: "+253",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DJF", name: "Djiboutian franc", symbol: "Fdj"),
      ],
      languages: <String>["French", "Arabic"],
      timezones: <String>["Africa/Djibouti"],
    ),
    Country(
      name: "Dominica",
      iso2: "DM",
      iso3: "DMA",
      region: "Americas",
      flagEmoji: "🇩🇲",
      dialCode: "+1767",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Dominica"],
    ),
    Country(
      name: "Dominican Republic",
      iso2: "DO",
      iso3: "DOM",
      region: "Americas",
      flagEmoji: "🇩🇴",
      dialCode: "+18091829",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DOP", name: "Dominican peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Santo_Domingo"],
    ),
    Country(
      name: "East Timor",
      iso2: "TL",
      iso3: "TLS",
      region: "Asia",
      flagEmoji: "🇹🇱",
      dialCode: "+670",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
        CurrencyInfo(code: "IDR", name: "", symbol: ""),
      ],
      languages: <String>["Tetum", "Portuguese"],
      timezones: <String>["Asia/Dili"],
    ),
    Country(
      name: "Ecuador",
      iso2: "EC",
      iso3: "ECU",
      region: "Americas",
      flagEmoji: "🇪🇨",
      dialCode: "+593",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Guayaquil", "Pacific/Galapagos"],
    ),
    Country(
      name: "Egypt",
      iso2: "EG",
      iso3: "EGY",
      region: "Africa",
      flagEmoji: "🇪🇬",
      dialCode: "+20",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EGP", name: "Egyptian pound", symbol: "ج.م"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Africa/Cairo"],
    ),
    Country(
      name: "El Salvador",
      iso2: "SV",
      iso3: "SLV",
      region: "Americas",
      flagEmoji: "🇸🇻",
      dialCode: "+503",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
        CurrencyInfo(code: "SVC", name: "", symbol: ""),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/El_Salvador"],
    ),
    Country(
      name: "Equatorial Guinea",
      iso2: "GQ",
      iso3: "GNQ",
      region: "Africa",
      flagEmoji: "🇬🇶",
      dialCode: "+240",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FCFA",
        ),
      ],
      languages: <String>["Spanish", "French", "Portuguese"],
      timezones: <String>["Africa/Malabo"],
    ),
    Country(
      name: "Eritrea",
      iso2: "ER",
      iso3: "ERI",
      region: "Africa",
      flagEmoji: "🇪🇷",
      dialCode: "+291",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ERN", name: "Eritrean nakfa", symbol: "Nfk"),
        CurrencyInfo(code: "ETB", name: "", symbol: ""),
      ],
      languages: <String>["Tigrinya", "Arabic", "English"],
      timezones: <String>["Africa/Asmara"],
    ),
    Country(
      name: "Estonia",
      iso2: "EE",
      iso3: "EST",
      region: "Europe",
      flagEmoji: "🇪🇪",
      dialCode: "+372",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Estonian"],
      timezones: <String>["Europe/Tallinn"],
    ),
    Country(
      name: "Ethiopia",
      iso2: "ET",
      iso3: "ETH",
      region: "Africa",
      flagEmoji: "🇪🇹",
      dialCode: "+251",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ETB", name: "Ethiopian birr", symbol: "Nkf"),
      ],
      languages: <String>["Amharic"],
      timezones: <String>["Africa/Addis_Ababa"],
    ),
    Country(
      name: "Falkland Islands",
      iso2: "FK",
      iso3: "FLK",
      region: "Americas",
      flagEmoji: "🇫🇰",
      dialCode: "+500",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "FKP", name: "Falkland Islands pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Atlantic/Stanley"],
    ),
    Country(
      name: "Faroe Islands",
      iso2: "FO",
      iso3: "FRO",
      region: "Europe",
      flagEmoji: "🇫🇴",
      dialCode: "+298",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DKK", name: "Danish krone", symbol: "Kr."),
      ],
      languages: <String>["Faroese", "Danish"],
      timezones: <String>["Atlantic/Faroe"],
    ),
    Country(
      name: "Fiji Islands",
      iso2: "FJ",
      iso3: "FJI",
      region: "Oceania",
      flagEmoji: "🇫🇯",
      dialCode: "+679",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "FJD", name: "Fijian dollar", symbol: "FJ\$"),
      ],
      languages: <String>["English", "Fijian", "Hindi", "Fiji Hindi"],
      timezones: <String>["Pacific/Fiji"],
    ),
    Country(
      name: "Finland",
      iso2: "FI",
      iso3: "FIN",
      region: "Europe",
      flagEmoji: "🇫🇮",
      dialCode: "+358",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Finnish", "Swedish"],
      timezones: <String>["Europe/Helsinki"],
    ),
    Country(
      name: "France",
      iso2: "FR",
      iso3: "FRA",
      region: "Europe",
      flagEmoji: "🇫🇷",
      dialCode: "+33",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["Europe/Paris"],
    ),
    Country(
      name: "French Guiana",
      iso2: "GF",
      iso3: "GUF",
      region: "Americas",
      flagEmoji: "🇬🇫",
      dialCode: "+594",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["America/Cayenne"],
    ),
    Country(
      name: "French Polynesia",
      iso2: "PF",
      iso3: "PYF",
      region: "Oceania",
      flagEmoji: "🇵🇫",
      dialCode: "+689",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "XPF", name: "CFP franc", symbol: "₣"),
      ],
      languages: <String>["French", "Tahitian"],
      timezones: <String>[
        "Pacific/Gambier",
        "Pacific/Marquesas",
        "Pacific/Tahiti",
      ],
    ),
    Country(
      name: "French Southern Territories",
      iso2: "TF",
      iso3: "ATF",
      region: "Africa",
      flagEmoji: "🇹🇫",
      dialCode: "+262",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["Indian/Kerguelen"],
    ),
    Country(
      name: "Gabon",
      iso2: "GA",
      iso3: "GAB",
      region: "Africa",
      flagEmoji: "🇬🇦",
      dialCode: "+241",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XAF",
          name: "Central African CFA franc",
          symbol: "FCFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Libreville"],
    ),
    Country(
      name: "Gambia The",
      iso2: "GM",
      iso3: "GMB",
      region: "Africa",
      flagEmoji: "🇬🇲",
      dialCode: "+220",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GMD", name: "Gambian dalasi", symbol: "D"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Banjul"],
    ),
    Country(
      name: "Georgia",
      iso2: "GE",
      iso3: "GEO",
      region: "Asia",
      flagEmoji: "🇬🇪",
      dialCode: "+995",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GEL", name: "Georgian lari", symbol: "ლ"),
      ],
      languages: <String>["Georgian"],
      timezones: <String>["Asia/Tbilisi"],
    ),
    Country(
      name: "Germany",
      iso2: "DE",
      iso3: "DEU",
      region: "Europe",
      flagEmoji: "🇩🇪",
      dialCode: "+49",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["German"],
      timezones: <String>["Europe/Berlin", "Europe/Busingen"],
    ),
    Country(
      name: "Ghana",
      iso2: "GH",
      iso3: "GHA",
      region: "Africa",
      flagEmoji: "🇬🇭",
      dialCode: "+233",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GHS", name: "Ghanaian cedi", symbol: "GH₵"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Accra"],
    ),
    Country(
      name: "Gibraltar",
      iso2: "GI",
      iso3: "GIB",
      region: "Europe",
      flagEmoji: "🇬🇮",
      dialCode: "+350",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GIP", name: "Gibraltar pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Europe/Gibraltar"],
    ),
    Country(
      name: "Greece",
      iso2: "GR",
      iso3: "GRC",
      region: "Europe",
      flagEmoji: "🇬🇷",
      dialCode: "+30",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Greek"],
      timezones: <String>["Europe/Athens"],
    ),
    Country(
      name: "Greenland",
      iso2: "GL",
      iso3: "GRL",
      region: "Americas",
      flagEmoji: "🇬🇱",
      dialCode: "+299",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "DKK", name: "Danish krone", symbol: "Kr."),
      ],
      languages: <String>["Greenlandic", "Danish"],
      timezones: <String>[
        "America/Danmarkshavn",
        "America/Nuuk",
        "America/Scoresbysund",
        "America/Thule",
      ],
    ),
    Country(
      name: "Grenada",
      iso2: "GD",
      iso3: "GRD",
      region: "Americas",
      flagEmoji: "🇬🇩",
      dialCode: "+1473",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Grenada"],
    ),
    Country(
      name: "Guadeloupe",
      iso2: "GP",
      iso3: "GLP",
      region: "Americas",
      flagEmoji: "🇬🇵",
      dialCode: "+590",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["America/Guadeloupe"],
    ),
    Country(
      name: "Guam",
      iso2: "GU",
      iso3: "GUM",
      region: "Oceania",
      flagEmoji: "🇬🇺",
      dialCode: "+1671",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "US Dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Chamorro"],
      timezones: <String>["Pacific/Guam"],
    ),
    Country(
      name: "Guatemala",
      iso2: "GT",
      iso3: "GTM",
      region: "Americas",
      flagEmoji: "🇬🇹",
      dialCode: "+502",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GTQ", name: "Guatemalan quetzal", symbol: "Q"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Guatemala"],
    ),
    Country(
      name: "Guernsey and Alderney",
      iso2: "GG",
      iso3: "GGY",
      region: "Europe",
      flagEmoji: "🇬🇬",
      dialCode: "+441481",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GBP", name: "British pound", symbol: "£"),
        CurrencyInfo(code: "GGP", name: "Guernsey Pound", symbol: "£"),
      ],
      languages: <String>["English", "French"],
      timezones: <String>["Europe/Guernsey"],
    ),
    Country(
      name: "Guinea",
      iso2: "GN",
      iso3: "GIN",
      region: "Africa",
      flagEmoji: "🇬🇳",
      dialCode: "+224",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GNF", name: "Guinean franc", symbol: "FG"),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Conakry"],
    ),
    Country(
      name: "Guinea-Bissau",
      iso2: "GW",
      iso3: "GNB",
      region: "Africa",
      flagEmoji: "🇬🇼",
      dialCode: "+245",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>["Africa/Bissau"],
    ),
    Country(
      name: "Guyana",
      iso2: "GY",
      iso3: "GUY",
      region: "Americas",
      flagEmoji: "🇬🇾",
      dialCode: "+592",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GYD", name: "Guyanese dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Guyana"],
    ),
    Country(
      name: "Haiti",
      iso2: "HT",
      iso3: "HTI",
      region: "Americas",
      flagEmoji: "🇭🇹",
      dialCode: "+509",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "HTG", name: "Haitian gourde", symbol: "G"),
      ],
      languages: <String>["French", "Haitian Creole"],
      timezones: <String>["America/Port-au-Prince"],
    ),
    Country(
      name: "Heard Island and McDonald Islands",
      iso2: "HM",
      iso3: "HMD",
      region: "Antarctica",
      flagEmoji: "🇭🇲",
      dialCode: "+672",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Indian/Kerguelen"],
    ),
    Country(
      name: "Honduras",
      iso2: "HN",
      iso3: "HND",
      region: "Americas",
      flagEmoji: "🇭🇳",
      dialCode: "+504",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "HNL", name: "Honduran lempira", symbol: "L"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Tegucigalpa"],
    ),
    Country(
      name: "Hong Kong S.A.R.",
      iso2: "HK",
      iso3: "HKG",
      region: "Asia",
      flagEmoji: "🇭🇰",
      dialCode: "+852",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "HKD", name: "Hong Kong dollar", symbol: "\$"),
      ],
      languages: <String>["Chinese (Cantonese)"],
      timezones: <String>["Asia/Hong_Kong"],
    ),
    Country(
      name: "Hungary",
      iso2: "HU",
      iso3: "HUN",
      region: "Europe",
      flagEmoji: "🇭🇺",
      dialCode: "+36",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "HUF", name: "Hungarian forint", symbol: "Ft"),
      ],
      languages: <String>["Hungarian"],
      timezones: <String>["Europe/Budapest"],
    ),
    Country(
      name: "Iceland",
      iso2: "IS",
      iso3: "ISL",
      region: "Europe",
      flagEmoji: "🇮🇸",
      dialCode: "+354",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ISK", name: "Icelandic króna", symbol: "kr"),
      ],
      languages: <String>["Icelandic"],
      timezones: <String>["Atlantic/Reykjavik"],
    ),
    Country(
      name: "India",
      iso2: "IN",
      iso3: "IND",
      region: "Asia",
      flagEmoji: "🇮🇳",
      dialCode: "+91",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "INR", name: "Indian rupee", symbol: "₹"),
      ],
      languages: <String>["Hindi", "English"],
      timezones: <String>["Asia/Kolkata"],
    ),
    Country(
      name: "Indonesia",
      iso2: "ID",
      iso3: "IDN",
      region: "Asia",
      flagEmoji: "🇮🇩",
      dialCode: "+62",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "IDR", name: "Indonesian rupiah", symbol: "Rp"),
      ],
      languages: <String>["Indonesian"],
      timezones: <String>[
        "Asia/Jakarta",
        "Asia/Jayapura",
        "Asia/Makassar",
        "Asia/Pontianak",
      ],
    ),
    Country(
      name: "Iran",
      iso2: "IR",
      iso3: "IRN",
      region: "Asia",
      flagEmoji: "🇮🇷",
      dialCode: "+98",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "IRR", name: "Iranian rial", symbol: "﷼"),
      ],
      languages: <String>["Persian"],
      timezones: <String>["Asia/Tehran"],
    ),
    Country(
      name: "Iraq",
      iso2: "IQ",
      iso3: "IRQ",
      region: "Asia",
      flagEmoji: "🇮🇶",
      dialCode: "+964",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "IQD", name: "Iraqi dinar", symbol: "د.ع"),
      ],
      languages: <String>["Arabic", "Kurdish"],
      timezones: <String>["Asia/Baghdad"],
    ),
    Country(
      name: "Ireland",
      iso2: "IE",
      iso3: "IRL",
      region: "Europe",
      flagEmoji: "🇮🇪",
      dialCode: "+353",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Irish", "English"],
      timezones: <String>["Europe/Dublin"],
    ),
    Country(
      name: "Israel",
      iso2: "IL",
      iso3: "ISR",
      region: "Asia",
      flagEmoji: "🇮🇱",
      dialCode: "+972",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ILS", name: "Israeli new shekel", symbol: "₪"),
      ],
      languages: <String>["Hebrew"],
      timezones: <String>["Asia/Jerusalem"],
    ),
    Country(
      name: "Italy",
      iso2: "IT",
      iso3: "ITA",
      region: "Europe",
      flagEmoji: "🇮🇹",
      dialCode: "+39",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Italian"],
      timezones: <String>["Europe/Rome"],
    ),
    Country(
      name: "Jamaica",
      iso2: "JM",
      iso3: "JAM",
      region: "Americas",
      flagEmoji: "🇯🇲",
      dialCode: "+1876",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "JMD", name: "Jamaican dollar", symbol: "J\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Jamaica"],
    ),
    Country(
      name: "Japan",
      iso2: "JP",
      iso3: "JPN",
      region: "Asia",
      flagEmoji: "🇯🇵",
      dialCode: "+81",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "JPY", name: "Japanese yen", symbol: "¥"),
      ],
      languages: <String>["Japanese"],
      timezones: <String>["Asia/Tokyo"],
    ),
    Country(
      name: "Jersey",
      iso2: "JE",
      iso3: "JEY",
      region: "Europe",
      flagEmoji: "🇯🇪",
      dialCode: "+441534",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GBP", name: "British pound", symbol: "£"),
      ],
      languages: <String>["English", "French"],
      timezones: <String>["Europe/Jersey"],
    ),
    Country(
      name: "Jordan",
      iso2: "JO",
      iso3: "JOR",
      region: "Asia",
      flagEmoji: "🇯🇴",
      dialCode: "+962",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "JOD", name: "Jordanian dinar", symbol: "ا.د"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Amman"],
    ),
    Country(
      name: "Kazakhstan",
      iso2: "KZ",
      iso3: "KAZ",
      region: "Asia",
      flagEmoji: "🇰🇿",
      dialCode: "+7",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KZT", name: "Kazakhstani tenge", symbol: "лв"),
      ],
      languages: <String>["Kazakh", "Russian"],
      timezones: <String>[
        "Asia/Almaty",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Atyrau",
        "Asia/Oral",
        "Asia/Qostanay",
        "Asia/Qyzylorda",
      ],
    ),
    Country(
      name: "Kenya",
      iso2: "KE",
      iso3: "KEN",
      region: "Africa",
      flagEmoji: "🇰🇪",
      dialCode: "+254",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KES", name: "Kenyan shilling", symbol: "KSh"),
      ],
      languages: <String>["Swahili", "English"],
      timezones: <String>["Africa/Nairobi"],
    ),
    Country(
      name: "Kiribati",
      iso2: "KI",
      iso3: "KIR",
      region: "Oceania",
      flagEmoji: "🇰🇮",
      dialCode: "+686",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Gilbertese"],
      timezones: <String>[
        "Pacific/Enderbury",
        "Pacific/Kiritimati",
        "Pacific/Tarawa",
      ],
    ),
    Country(
      name: "Kosovo",
      iso2: "XK",
      iso3: "XKX",
      region: "Europe",
      flagEmoji: "🇽🇰",
      dialCode: "+383",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Albanian", "Serbian"],
      timezones: <String>["Europe/Belgrade"],
    ),
    Country(
      name: "Kuwait",
      iso2: "KW",
      iso3: "KWT",
      region: "Asia",
      flagEmoji: "🇰🇼",
      dialCode: "+965",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KWD", name: "Kuwaiti dinar", symbol: "ك.د"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Kuwait"],
    ),
    Country(
      name: "Kyrgyzstan",
      iso2: "KG",
      iso3: "KGZ",
      region: "Asia",
      flagEmoji: "🇰🇬",
      dialCode: "+996",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KGS", name: "Kyrgyzstani som", symbol: "лв"),
      ],
      languages: <String>["Kyrgyz", "Russian"],
      timezones: <String>["Asia/Bishkek"],
    ),
    Country(
      name: "Laos",
      iso2: "LA",
      iso3: "LAO",
      region: "Asia",
      flagEmoji: "🇱🇦",
      dialCode: "+856",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LAK", name: "Lao kip", symbol: "₭"),
      ],
      languages: <String>["Lao"],
      timezones: <String>["Asia/Vientiane"],
    ),
    Country(
      name: "Latvia",
      iso2: "LV",
      iso3: "LVA",
      region: "Europe",
      flagEmoji: "🇱🇻",
      dialCode: "+371",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Latvian"],
      timezones: <String>["Europe/Riga"],
    ),
    Country(
      name: "Lebanon",
      iso2: "LB",
      iso3: "LBN",
      region: "Asia",
      flagEmoji: "🇱🇧",
      dialCode: "+961",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LBP", name: "Lebanese pound", symbol: "£"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Beirut"],
    ),
    Country(
      name: "Lesotho",
      iso2: "LS",
      iso3: "LSO",
      region: "Africa",
      flagEmoji: "🇱🇸",
      dialCode: "+266",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LSL", name: "Lesotho loti", symbol: "L"),
        CurrencyInfo(code: "ZAR", name: "", symbol: ""),
      ],
      languages: <String>["Sesotho", "English"],
      timezones: <String>["Africa/Maseru"],
    ),
    Country(
      name: "Liberia",
      iso2: "LR",
      iso3: "LBR",
      region: "Africa",
      flagEmoji: "🇱🇷",
      dialCode: "+231",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LRD", name: "Liberian dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Monrovia"],
    ),
    Country(
      name: "Libya",
      iso2: "LY",
      iso3: "LBY",
      region: "Africa",
      flagEmoji: "🇱🇾",
      dialCode: "+218",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LYD", name: "Libyan dinar", symbol: "د.ل"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Africa/Tripoli"],
    ),
    Country(
      name: "Liechtenstein",
      iso2: "LI",
      iso3: "LIE",
      region: "Europe",
      flagEmoji: "🇱🇮",
      dialCode: "+423",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CHF", name: "Swiss franc", symbol: "CHf"),
      ],
      languages: <String>["German"],
      timezones: <String>["Europe/Vaduz"],
    ),
    Country(
      name: "Lithuania",
      iso2: "LT",
      iso3: "LTU",
      region: "Europe",
      flagEmoji: "🇱🇹",
      dialCode: "+370",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Lithuanian"],
      timezones: <String>["Europe/Vilnius"],
    ),
    Country(
      name: "Luxembourg",
      iso2: "LU",
      iso3: "LUX",
      region: "Europe",
      flagEmoji: "🇱🇺",
      dialCode: "+352",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Luxembourgish", "French", "German"],
      timezones: <String>["Europe/Luxembourg"],
    ),
    Country(
      name: "Macau S.A.R.",
      iso2: "MO",
      iso3: "MAC",
      region: "Asia",
      flagEmoji: "🇲🇴",
      dialCode: "+853",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MOP", name: "Macanese pataca", symbol: "\$"),
      ],
      languages: <String>["Chinese", "Portuguese"],
      timezones: <String>["Asia/Macau"],
    ),
    Country(
      name: "Madagascar",
      iso2: "MG",
      iso3: "MDG",
      region: "Africa",
      flagEmoji: "🇲🇬",
      dialCode: "+261",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MGA", name: "Malagasy ariary", symbol: "Ar"),
      ],
      languages: <String>["Malagasy", "French"],
      timezones: <String>["Indian/Antananarivo"],
    ),
    Country(
      name: "Malawi",
      iso2: "MW",
      iso3: "MWI",
      region: "Africa",
      flagEmoji: "🇲🇼",
      dialCode: "+265",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MWK", name: "Malawian kwacha", symbol: "MK"),
      ],
      languages: <String>["Chichewa", "English"],
      timezones: <String>["Africa/Blantyre"],
    ),
    Country(
      name: "Malaysia",
      iso2: "MY",
      iso3: "MYS",
      region: "Asia",
      flagEmoji: "🇲🇾",
      dialCode: "+60",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MYR", name: "Malaysian ringgit", symbol: "RM"),
      ],
      languages: <String>["Malay"],
      timezones: <String>["Asia/Kuala_Lumpur", "Asia/Kuching"],
    ),
    Country(
      name: "Maldives",
      iso2: "MV",
      iso3: "MDV",
      region: "Asia",
      flagEmoji: "🇲🇻",
      dialCode: "+960",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MVR", name: "Maldivian rufiyaa", symbol: "Rf"),
      ],
      languages: <String>["Dhivehi", "Divehi"],
      timezones: <String>["Indian/Maldives"],
    ),
    Country(
      name: "Mali",
      iso2: "ML",
      iso3: "MLI",
      region: "Africa",
      flagEmoji: "🇲🇱",
      dialCode: "+223",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Bamako"],
    ),
    Country(
      name: "Malta",
      iso2: "MT",
      iso3: "MLT",
      region: "Europe",
      flagEmoji: "🇲🇹",
      dialCode: "+356",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Maltese", "English"],
      timezones: <String>["Europe/Malta"],
    ),
    Country(
      name: "Man (Isle of)",
      iso2: "IM",
      iso3: "IMN",
      region: "Europe",
      flagEmoji: "🇮🇲",
      dialCode: "+441624",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GBP", name: "British pound", symbol: "£"),
      ],
      languages: <String>["English", "Manx"],
      timezones: <String>["Europe/Isle_of_Man"],
    ),
    Country(
      name: "Marshall Islands",
      iso2: "MH",
      iso3: "MHL",
      region: "Oceania",
      flagEmoji: "🇲🇭",
      dialCode: "+692",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["Marshallese", "English"],
      timezones: <String>["Pacific/Kwajalein", "Pacific/Majuro"],
    ),
    Country(
      name: "Martinique",
      iso2: "MQ",
      iso3: "MTQ",
      region: "Americas",
      flagEmoji: "🇲🇶",
      dialCode: "+596",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["America/Martinique"],
    ),
    Country(
      name: "Mauritania",
      iso2: "MR",
      iso3: "MRT",
      region: "Africa",
      flagEmoji: "🇲🇷",
      dialCode: "+222",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MRO", name: "Mauritanian ouguiya", symbol: "MRU"),
        CurrencyInfo(code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Africa/Nouakchott"],
    ),
    Country(
      name: "Mauritius",
      iso2: "MU",
      iso3: "MUS",
      region: "Africa",
      flagEmoji: "🇲🇺",
      dialCode: "+230",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MUR", name: "Mauritian rupee", symbol: "₨"),
      ],
      languages: <String>["English", "French"],
      timezones: <String>["Indian/Mauritius"],
    ),
    Country(
      name: "Mayotte",
      iso2: "YT",
      iso3: "MYT",
      region: "Africa",
      flagEmoji: "🇾🇹",
      dialCode: "+262",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["Indian/Mayotte"],
    ),
    Country(
      name: "Mexico",
      iso2: "MX",
      iso3: "MEX",
      region: "Americas",
      flagEmoji: "🇲🇽",
      dialCode: "+52",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MXN", name: "Mexican peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>[
        "America/Bahia_Banderas",
        "America/Cancun",
        "America/Chihuahua",
        "America/Hermosillo",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Merida",
        "America/Mexico_City",
        "America/Monterrey",
        "America/Ojinaga",
        "America/Tijuana",
      ],
    ),
    Country(
      name: "Micronesia",
      iso2: "FM",
      iso3: "FSM",
      region: "Oceania",
      flagEmoji: "🇫🇲",
      dialCode: "+691",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"],
    ),
    Country(
      name: "Moldova",
      iso2: "MD",
      iso3: "MDA",
      region: "Europe",
      flagEmoji: "🇲🇩",
      dialCode: "+373",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MDL", name: "Moldovan leu", symbol: "L"),
      ],
      languages: <String>["Moldovan (Romanian)", "Romanian"],
      timezones: <String>["Europe/Chisinau"],
    ),
    Country(
      name: "Monaco",
      iso2: "MC",
      iso3: "MCO",
      region: "Europe",
      flagEmoji: "🇲🇨",
      dialCode: "+377",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["Europe/Monaco"],
    ),
    Country(
      name: "Mongolia",
      iso2: "MN",
      iso3: "MNG",
      region: "Asia",
      flagEmoji: "🇲🇳",
      dialCode: "+976",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MNT", name: "Mongolian tögrög", symbol: "₮"),
      ],
      languages: <String>["Mongolian"],
      timezones: <String>["Asia/Choibalsan", "Asia/Hovd", "Asia/Ulaanbaatar"],
    ),
    Country(
      name: "Montenegro",
      iso2: "ME",
      iso3: "MNE",
      region: "Europe",
      flagEmoji: "🇲🇪",
      dialCode: "+382",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Montenegrin", "Montenegrin language"],
      timezones: <String>["Europe/Podgorica"],
    ),
    Country(
      name: "Montserrat",
      iso2: "MS",
      iso3: "MSR",
      region: "Americas",
      flagEmoji: "🇲🇸",
      dialCode: "+1664",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Montserrat"],
    ),
    Country(
      name: "Morocco",
      iso2: "MA",
      iso3: "MAR",
      region: "Africa",
      flagEmoji: "🇲🇦",
      dialCode: "+212",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MAD", name: "Moroccan dirham", symbol: "DH"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Africa/Casablanca"],
    ),
    Country(
      name: "Mozambique",
      iso2: "MZ",
      iso3: "MOZ",
      region: "Africa",
      flagEmoji: "🇲🇿",
      dialCode: "+258",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MZN", name: "Mozambican metical", symbol: "MT"),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>["Africa/Maputo"],
    ),
    Country(
      name: "Myanmar",
      iso2: "MM",
      iso3: "MMR",
      region: "Asia",
      flagEmoji: "🇲🇲",
      dialCode: "+95",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MMK", name: "Burmese kyat", symbol: "K"),
      ],
      languages: <String>["Burmese"],
      timezones: <String>["Asia/Yangon"],
    ),
    Country(
      name: "Namibia",
      iso2: "NA",
      iso3: "NAM",
      region: "Africa",
      flagEmoji: "🇳🇦",
      dialCode: "+264",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NAD", name: "Namibian dollar", symbol: "\$"),
        CurrencyInfo(code: "ZAR", name: "", symbol: ""),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Windhoek"],
    ),
    Country(
      name: "Nauru",
      iso2: "NR",
      iso3: "NRU",
      region: "Oceania",
      flagEmoji: "🇳🇷",
      dialCode: "+674",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["Nauruan", "English"],
      timezones: <String>["Pacific/Nauru"],
    ),
    Country(
      name: "Nepal",
      iso2: "NP",
      iso3: "NPL",
      region: "Asia",
      flagEmoji: "🇳🇵",
      dialCode: "+977",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NPR", name: "Nepalese rupee", symbol: "₨"),
      ],
      languages: <String>["Nepali"],
      timezones: <String>["Asia/Kathmandu"],
    ),
    Country(
      name: "Netherlands",
      iso2: "NL",
      iso3: "NLD",
      region: "Europe",
      flagEmoji: "🇳🇱",
      dialCode: "+31",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Dutch"],
      timezones: <String>["Europe/Amsterdam"],
    ),
    Country(
      name: "New Caledonia",
      iso2: "NC",
      iso3: "NCL",
      region: "Oceania",
      flagEmoji: "🇳🇨",
      dialCode: "+687",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "XPF", name: "CFP franc", symbol: "₣"),
      ],
      languages: <String>["French"],
      timezones: <String>["Pacific/Noumea"],
    ),
    Country(
      name: "New Zealand",
      iso2: "NZ",
      iso3: "NZL",
      region: "Oceania",
      flagEmoji: "🇳🇿",
      dialCode: "+64",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NZD", name: "New Zealand dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Pacific/Auckland", "Pacific/Chatham"],
    ),
    Country(
      name: "Nicaragua",
      iso2: "NI",
      iso3: "NIC",
      region: "Americas",
      flagEmoji: "🇳🇮",
      dialCode: "+505",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NIO", name: "Nicaraguan córdoba", symbol: "C\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Managua"],
    ),
    Country(
      name: "Niger",
      iso2: "NE",
      iso3: "NER",
      region: "Africa",
      flagEmoji: "🇳🇪",
      dialCode: "+227",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Niamey"],
    ),
    Country(
      name: "Nigeria",
      iso2: "NG",
      iso3: "NGA",
      region: "Africa",
      flagEmoji: "🇳🇬",
      dialCode: "+234",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NGN", name: "Nigerian naira", symbol: "₦"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Lagos"],
    ),
    Country(
      name: "Niue",
      iso2: "NU",
      iso3: "NIU",
      region: "Oceania",
      flagEmoji: "🇳🇺",
      dialCode: "+683",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NZD", name: "New Zealand dollar", symbol: "\$"),
      ],
      languages: <String>["Niuean", "English"],
      timezones: <String>["Pacific/Niue"],
    ),
    Country(
      name: "Norfolk Island",
      iso2: "NF",
      iso3: "NFK",
      region: "Oceania",
      flagEmoji: "🇳🇫",
      dialCode: "+672",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Norfuk"],
      timezones: <String>["Pacific/Norfolk"],
    ),
    Country(
      name: "North Korea",
      iso2: "KP",
      iso3: "PRK",
      region: "Asia",
      flagEmoji: "🇰🇵",
      dialCode: "+850",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KPW", name: "North Korean Won", symbol: "₩"),
      ],
      languages: <String>["Korean"],
      timezones: <String>["Asia/Pyongyang"],
    ),
    Country(
      name: "North Macedonia",
      iso2: "MK",
      iso3: "MKD",
      region: "Europe",
      flagEmoji: "🇲🇰",
      dialCode: "+389",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MKD", name: "Denar", symbol: "ден"),
      ],
      languages: <String>["Macedonian"],
      timezones: <String>["Europe/Skopje"],
    ),
    Country(
      name: "Northern Mariana Islands",
      iso2: "MP",
      iso3: "MNP",
      region: "Oceania",
      flagEmoji: "🇲🇵",
      dialCode: "+1670",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Chamorro", "Carolinian"],
      timezones: <String>["Pacific/Saipan"],
    ),
    Country(
      name: "Norway",
      iso2: "NO",
      iso3: "NOR",
      region: "Europe",
      flagEmoji: "🇳🇴",
      dialCode: "+47",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NOK", name: "Norwegian krone", symbol: "kr"),
      ],
      languages: <String>["Norwegian"],
      timezones: <String>["Europe/Oslo"],
    ),
    Country(
      name: "Oman",
      iso2: "OM",
      iso3: "OMN",
      region: "Asia",
      flagEmoji: "🇴🇲",
      dialCode: "+968",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "OMR", name: "Omani rial", symbol: ".ع.ر"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Muscat"],
    ),
    Country(
      name: "Pakistan",
      iso2: "PK",
      iso3: "PAK",
      region: "Asia",
      flagEmoji: "🇵🇰",
      dialCode: "+92",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PKR", name: "Pakistani rupee", symbol: "₨"),
      ],
      languages: <String>["Urdu", "English"],
      timezones: <String>["Asia/Karachi"],
    ),
    Country(
      name: "Palau",
      iso2: "PW",
      iso3: "PLW",
      region: "Oceania",
      flagEmoji: "🇵🇼",
      dialCode: "+680",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["Palauan", "English"],
      timezones: <String>["Pacific/Palau"],
    ),
    Country(
      name: "Palestinian Territory Occupied",
      iso2: "PS",
      iso3: "PSE",
      region: "Asia",
      flagEmoji: "🇵🇸",
      dialCode: "+970",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ILS", name: "Israeli new shekel", symbol: "₪"),
        CurrencyInfo(code: "EGP", name: "", symbol: ""),
        CurrencyInfo(code: "JOD", name: "", symbol: ""),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Gaza", "Asia/Hebron"],
    ),
    Country(
      name: "Panama",
      iso2: "PA",
      iso3: "PAN",
      region: "Americas",
      flagEmoji: "🇵🇦",
      dialCode: "+507",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PAB", name: "Panamanian balboa", symbol: "B/."),
        CurrencyInfo(code: "USD", name: "", symbol: ""),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Panama"],
    ),
    Country(
      name: "Papua new Guinea",
      iso2: "PG",
      iso3: "PNG",
      region: "Oceania",
      flagEmoji: "🇵🇬",
      dialCode: "+675",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PGK", name: "Papua New Guinean kina", symbol: "K"),
      ],
      languages: <String>["English", "Tok Pisin", "Hiri Motu"],
      timezones: <String>["Pacific/Bougainville", "Pacific/Port_Moresby"],
    ),
    Country(
      name: "Paraguay",
      iso2: "PY",
      iso3: "PRY",
      region: "Americas",
      flagEmoji: "🇵🇾",
      dialCode: "+595",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PYG", name: "Paraguayan guarani", symbol: "₲"),
      ],
      languages: <String>["Spanish", "Guaraní"],
      timezones: <String>["America/Asuncion"],
    ),
    Country(
      name: "Peru",
      iso2: "PE",
      iso3: "PER",
      region: "Americas",
      flagEmoji: "🇵🇪",
      dialCode: "+51",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PEN", name: "Peruvian sol", symbol: "S/."),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Lima"],
    ),
    Country(
      name: "Philippines",
      iso2: "PH",
      iso3: "PHL",
      region: "Asia",
      flagEmoji: "🇵🇭",
      dialCode: "+63",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PHP", name: "Philippine peso", symbol: "₱"),
      ],
      languages: <String>["Filipino", "English"],
      timezones: <String>["Asia/Manila"],
    ),
    Country(
      name: "Pitcairn Island",
      iso2: "PN",
      iso3: "PCN",
      region: "Oceania",
      flagEmoji: "🇵🇳",
      dialCode: "+870",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NZD", name: "New Zealand dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Pacific/Pitcairn"],
    ),
    Country(
      name: "Poland",
      iso2: "PL",
      iso3: "POL",
      region: "Europe",
      flagEmoji: "🇵🇱",
      dialCode: "+48",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "PLN", name: "Polish złoty", symbol: "zł"),
      ],
      languages: <String>["Polish"],
      timezones: <String>["Europe/Warsaw"],
    ),
    Country(
      name: "Portugal",
      iso2: "PT",
      iso3: "PRT",
      region: "Europe",
      flagEmoji: "🇵🇹",
      dialCode: "+351",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>[
        "Atlantic/Azores",
        "Atlantic/Madeira",
        "Europe/Lisbon",
      ],
    ),
    Country(
      name: "Puerto Rico",
      iso2: "PR",
      iso3: "PRI",
      region: "Americas",
      flagEmoji: "🇵🇷",
      dialCode: "+17871939",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["Spanish", "English"],
      timezones: <String>["America/Puerto_Rico"],
    ),
    Country(
      name: "Qatar",
      iso2: "QA",
      iso3: "QAT",
      region: "Asia",
      flagEmoji: "🇶🇦",
      dialCode: "+974",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "QAR", name: "Qatari riyal", symbol: "ق.ر"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Qatar"],
    ),
    Country(
      name: "Reunion",
      iso2: "RE",
      iso3: "REU",
      region: "Africa",
      flagEmoji: "🇷🇪",
      dialCode: "+262",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["Indian/Reunion"],
    ),
    Country(
      name: "Romania",
      iso2: "RO",
      iso3: "ROU",
      region: "Europe",
      flagEmoji: "🇷🇴",
      dialCode: "+40",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "RON", name: "Romanian leu", symbol: "lei"),
      ],
      languages: <String>["Romanian"],
      timezones: <String>["Europe/Bucharest"],
    ),
    Country(
      name: "Russia",
      iso2: "RU",
      iso3: "RUS",
      region: "Europe",
      flagEmoji: "🇷🇺",
      dialCode: "+7",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "RUB", name: "Russian ruble", symbol: "₽"),
      ],
      languages: <String>["Russian"],
      timezones: <String>[
        "Asia/Anadyr",
        "Asia/Barnaul",
        "Asia/Chita",
        "Asia/Irkutsk",
        "Asia/Kamchatka",
        "Asia/Khandyga",
        "Asia/Krasnoyarsk",
        "Asia/Magadan",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Omsk",
        "Asia/Sakhalin",
        "Asia/Srednekolymsk",
        "Asia/Tomsk",
        "Asia/Ust-Nera",
        "Asia/Vladivostok",
        "Asia/Yakutsk",
        "Asia/Yekaterinburg",
        "Europe/Astrakhan",
        "Europe/Kaliningrad",
        "Europe/Kirov",
        "Europe/Moscow",
        "Europe/Samara",
        "Europe/Saratov",
        "Europe/Ulyanovsk",
        "Europe/Volgograd",
      ],
    ),
    Country(
      name: "Rwanda",
      iso2: "RW",
      iso3: "RWA",
      region: "Africa",
      flagEmoji: "🇷🇼",
      dialCode: "+250",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "RWF", name: "Rwandan franc", symbol: "FRw"),
      ],
      languages: <String>["Kinyarwanda", "French", "English", "Swahili"],
      timezones: <String>["Africa/Kigali"],
    ),
    Country(
      name: "Saint Helena",
      iso2: "SH",
      iso3: "SHN",
      region: "Africa",
      flagEmoji: "🇸🇭",
      dialCode: "+290",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SHP", name: "Saint Helena pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Atlantic/St_Helena"],
    ),
    Country(
      name: "Saint Kitts And Nevis",
      iso2: "KN",
      iso3: "KNA",
      region: "Americas",
      flagEmoji: "🇰🇳",
      dialCode: "+1869",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/St_Kitts"],
    ),
    Country(
      name: "Saint Lucia",
      iso2: "LC",
      iso3: "LCA",
      region: "Americas",
      flagEmoji: "🇱🇨",
      dialCode: "+1758",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/St_Lucia"],
    ),
    Country(
      name: "Saint Pierre and Miquelon",
      iso2: "PM",
      iso3: "SPM",
      region: "Americas",
      flagEmoji: "🇵🇲",
      dialCode: "+508",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["America/Miquelon"],
    ),
    Country(
      name: "Saint Vincent And The Grenadines",
      iso2: "VC",
      iso3: "VCT",
      region: "Americas",
      flagEmoji: "🇻🇨",
      dialCode: "+1784",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XCD",
          name: "Eastern Caribbean dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/St_Vincent"],
    ),
    Country(
      name: "Saint-Barthelemy",
      iso2: "BL",
      iso3: "BLM",
      region: "Americas",
      flagEmoji: "🇧🇱",
      dialCode: "+590",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French"],
      timezones: <String>["America/St_Barthelemy"],
    ),
    Country(
      name: "Saint-Martin (French part)",
      iso2: "MF",
      iso3: "MAF",
      region: "Americas",
      flagEmoji: "🇲🇫",
      dialCode: "+590",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["French", "English", "Dutch"],
      timezones: <String>["America/Marigot"],
    ),
    Country(
      name: "Samoa",
      iso2: "WS",
      iso3: "WSM",
      region: "Oceania",
      flagEmoji: "🇼🇸",
      dialCode: "+685",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "WST", name: "Samoan tālā", symbol: "SAT"),
      ],
      languages: <String>["Samoan", "English"],
      timezones: <String>["Pacific/Apia"],
    ),
    Country(
      name: "San Marino",
      iso2: "SM",
      iso3: "SMR",
      region: "Europe",
      flagEmoji: "🇸🇲",
      dialCode: "+378",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Italian"],
      timezones: <String>["Europe/San_Marino"],
    ),
    Country(
      name: "Sao Tome and Principe",
      iso2: "ST",
      iso3: "STP",
      region: "Africa",
      flagEmoji: "🇸🇹",
      dialCode: "+239",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "STD", name: "Dobra", symbol: "Db"),
        CurrencyInfo(
          code: "STN",
          name: "São Tomé and Príncipe Dobra",
          symbol: "Db",
        ),
      ],
      languages: <String>["Portuguese"],
      timezones: <String>["Africa/Sao_Tome"],
    ),
    Country(
      name: "Saudi Arabia",
      iso2: "SA",
      iso3: "SAU",
      region: "Asia",
      flagEmoji: "🇸🇦",
      dialCode: "+966",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SAR", name: "Saudi riyal", symbol: "﷼"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Riyadh"],
    ),
    Country(
      name: "Senegal",
      iso2: "SN",
      iso3: "SEN",
      region: "Africa",
      flagEmoji: "🇸🇳",
      dialCode: "+221",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Dakar"],
    ),
    Country(
      name: "Serbia",
      iso2: "RS",
      iso3: "SRB",
      region: "Europe",
      flagEmoji: "🇷🇸",
      dialCode: "+381",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "RSD", name: "Serbian dinar", symbol: "din"),
      ],
      languages: <String>["Serbian"],
      timezones: <String>["Europe/Belgrade"],
    ),
    Country(
      name: "Seychelles",
      iso2: "SC",
      iso3: "SYC",
      region: "Africa",
      flagEmoji: "🇸🇨",
      dialCode: "+248",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SCR", name: "Seychellois rupee", symbol: "SRe"),
      ],
      languages: <String>["Seychellois Creole", "English", "French"],
      timezones: <String>["Indian/Mahe"],
    ),
    Country(
      name: "Sierra Leone",
      iso2: "SL",
      iso3: "SLE",
      region: "Africa",
      flagEmoji: "🇸🇱",
      dialCode: "+232",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SLL", name: "Sierra Leonean leone", symbol: "Le"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Freetown"],
    ),
    Country(
      name: "Singapore",
      iso2: "SG",
      iso3: "SGP",
      region: "Asia",
      flagEmoji: "🇸🇬",
      dialCode: "+65",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SGD", name: "Singapore dollar", symbol: "\$"),
      ],
      languages: <String>["English", "Malay", "Mandarin", "Tamil"],
      timezones: <String>["Asia/Singapore"],
    ),
    Country(
      name: "Sint Maarten (Dutch part)",
      iso2: "SX",
      iso3: "SXM",
      region: "Americas",
      flagEmoji: "🇸🇽",
      dialCode: "+1721",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "ANG",
          name: "Netherlands Antillean guilder",
          symbol: "ƒ",
        ),
      ],
      languages: <String>["Dutch", "English"],
      timezones: <String>["America/Anguilla"],
    ),
    Country(
      name: "Slovakia",
      iso2: "SK",
      iso3: "SVK",
      region: "Europe",
      flagEmoji: "🇸🇰",
      dialCode: "+421",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Slovak"],
      timezones: <String>["Europe/Bratislava"],
    ),
    Country(
      name: "Slovenia",
      iso2: "SI",
      iso3: "SVN",
      region: "Europe",
      flagEmoji: "🇸🇮",
      dialCode: "+386",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Slovene", "Slovene language"],
      timezones: <String>["Europe/Ljubljana"],
    ),
    Country(
      name: "Solomon Islands",
      iso2: "SB",
      iso3: "SLB",
      region: "Oceania",
      flagEmoji: "🇸🇧",
      dialCode: "+677",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "SBD",
          name: "Solomon Islands dollar",
          symbol: "Si\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["Pacific/Guadalcanal"],
    ),
    Country(
      name: "Somalia",
      iso2: "SO",
      iso3: "SOM",
      region: "Africa",
      flagEmoji: "🇸🇴",
      dialCode: "+252",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SOS", name: "Somali shilling", symbol: "Sh.so."),
      ],
      languages: <String>["Somali", "Arabic"],
      timezones: <String>["Africa/Mogadishu"],
    ),
    Country(
      name: "South Africa",
      iso2: "ZA",
      iso3: "ZAF",
      region: "Africa",
      flagEmoji: "🇿🇦",
      dialCode: "+27",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ZAR", name: "South African rand", symbol: "R"),
      ],
      languages: <String>[
        "Afrikaans",
        "English",
        "isiNdebele",
        "isiXhosa",
        "isiZulu",
        "Sesotho",
        "Setswana",
        "siSwati",
        "Tshivenda",
        "Xitsonga",
      ],
      timezones: <String>["Africa/Johannesburg"],
    ),
    Country(
      name: "South Georgia",
      iso2: "GS",
      iso3: "SGS",
      region: "Americas",
      flagEmoji: "🇬🇸",
      dialCode: "+500",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GBP", name: "British pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Atlantic/South_Georgia"],
    ),
    Country(
      name: "South Korea",
      iso2: "KR",
      iso3: "KOR",
      region: "Asia",
      flagEmoji: "🇰🇷",
      dialCode: "+82",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "KRW", name: "Won", symbol: "₩"),
      ],
      languages: <String>["Korean"],
      timezones: <String>["Asia/Seoul"],
    ),
    Country(
      name: "South Sudan",
      iso2: "SS",
      iso3: "SSD",
      region: "Africa",
      flagEmoji: "🇸🇸",
      dialCode: "+211",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SSP", name: "South Sudanese pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Juba"],
    ),
    Country(
      name: "Spain",
      iso2: "ES",
      iso3: "ESP",
      region: "Europe",
      flagEmoji: "🇪🇸",
      dialCode: "+34",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"],
    ),
    Country(
      name: "Sri Lanka",
      iso2: "LK",
      iso3: "LKA",
      region: "Asia",
      flagEmoji: "🇱🇰",
      dialCode: "+94",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "LKR", name: "Sri Lankan rupee", symbol: "Rs"),
      ],
      languages: <String>["Sinhala", "Tamil"],
      timezones: <String>["Asia/Colombo"],
    ),
    Country(
      name: "Sudan",
      iso2: "SD",
      iso3: "SDN",
      region: "Africa",
      flagEmoji: "🇸🇩",
      dialCode: "+249",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SDG", name: "Sudanese pound", symbol: ".س.ج"),
      ],
      languages: <String>["Arabic", "English"],
      timezones: <String>["Africa/Khartoum"],
    ),
    Country(
      name: "Suriname",
      iso2: "SR",
      iso3: "SUR",
      region: "Americas",
      flagEmoji: "🇸🇷",
      dialCode: "+597",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SRD", name: "Surinamese dollar", symbol: "\$"),
      ],
      languages: <String>["Dutch"],
      timezones: <String>["America/Paramaribo"],
    ),
    Country(
      name: "Svalbard And Jan Mayen Islands",
      iso2: "SJ",
      iso3: "SJM",
      region: "Europe",
      flagEmoji: "🇸🇯",
      dialCode: "+47",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NOK", name: "Norwegian Krone", symbol: "kr"),
      ],
      languages: <String>["Norwegian"],
      timezones: <String>["Arctic/Longyearbyen"],
    ),
    Country(
      name: "Swaziland",
      iso2: "SZ",
      iso3: "SWZ",
      region: "Africa",
      flagEmoji: "🇸🇿",
      dialCode: "+268",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SZL", name: "Lilangeni", symbol: "E"),
      ],
      languages: <String>["Swazi", "English"],
      timezones: <String>["Africa/Mbabane"],
    ),
    Country(
      name: "Sweden",
      iso2: "SE",
      iso3: "SWE",
      region: "Europe",
      flagEmoji: "🇸🇪",
      dialCode: "+46",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SEK", name: "Swedish krona", symbol: "kr"),
      ],
      languages: <String>["Swedish"],
      timezones: <String>["Europe/Stockholm"],
    ),
    Country(
      name: "Switzerland",
      iso2: "CH",
      iso3: "CHE",
      region: "Europe",
      flagEmoji: "🇨🇭",
      dialCode: "+41",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "CHF", name: "Swiss franc", symbol: "CHf"),
      ],
      languages: <String>["German", "French", "Italian", "Romansh"],
      timezones: <String>["Europe/Zurich"],
    ),
    Country(
      name: "Syria",
      iso2: "SY",
      iso3: "SYR",
      region: "Asia",
      flagEmoji: "🇸🇾",
      dialCode: "+963",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SYP", name: "Syrian pound", symbol: "LS"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Damascus"],
    ),
    Country(
      name: "Taiwan",
      iso2: "TW",
      iso3: "TWN",
      region: "Asia",
      flagEmoji: "🇹🇼",
      dialCode: "+886",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TWD", name: "New Taiwan dollar", symbol: "\$"),
      ],
      languages: <String>["Mandarin"],
      timezones: <String>["Asia/Taipei"],
    ),
    Country(
      name: "Tajikistan",
      iso2: "TJ",
      iso3: "TJK",
      region: "Asia",
      flagEmoji: "🇹🇯",
      dialCode: "+992",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TJS", name: "Tajikistani somoni", symbol: "SM"),
        CurrencyInfo(code: "RUB", name: "", symbol: ""),
      ],
      languages: <String>["Tajik", "Persian"],
      timezones: <String>["Asia/Dushanbe"],
    ),
    Country(
      name: "Tanzania",
      iso2: "TZ",
      iso3: "TZA",
      region: "Africa",
      flagEmoji: "🇹🇿",
      dialCode: "+255",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TZS", name: "Tanzanian shilling", symbol: "TSh"),
      ],
      languages: <String>["Swahili", "English"],
      timezones: <String>["Africa/Dar_es_Salaam"],
    ),
    Country(
      name: "Thailand",
      iso2: "TH",
      iso3: "THA",
      region: "Asia",
      flagEmoji: "🇹🇭",
      dialCode: "+66",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "THB", name: "Thai baht", symbol: "฿"),
      ],
      languages: <String>["Thai"],
      timezones: <String>["Asia/Bangkok"],
    ),
    Country(
      name: "The Bahamas",
      iso2: "BS",
      iso3: "BHS",
      region: "Americas",
      flagEmoji: "🇧🇸",
      dialCode: "+1242",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "BSD", name: "Bahamian dollar", symbol: "B\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Nassau"],
    ),
    Country(
      name: "Togo",
      iso2: "TG",
      iso3: "TGO",
      region: "Africa",
      flagEmoji: "🇹🇬",
      dialCode: "+228",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "XOF",
          name: "West African CFA franc",
          symbol: "CFA",
        ),
      ],
      languages: <String>["French"],
      timezones: <String>["Africa/Lome"],
    ),
    Country(
      name: "Tokelau",
      iso2: "TK",
      iso3: "TKL",
      region: "Oceania",
      flagEmoji: "🇹🇰",
      dialCode: "+690",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "NZD", name: "New Zealand dollar", symbol: "\$"),
      ],
      languages: <String>["Tokelauan", "English"],
      timezones: <String>["Pacific/Fakaofo"],
    ),
    Country(
      name: "Tonga",
      iso2: "TO",
      iso3: "TON",
      region: "Oceania",
      flagEmoji: "🇹🇴",
      dialCode: "+676",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TOP", name: "Tongan paʻanga", symbol: "\$"),
      ],
      languages: <String>["Tongan", "English"],
      timezones: <String>["Pacific/Tongatapu"],
    ),
    Country(
      name: "Trinidad And Tobago",
      iso2: "TT",
      iso3: "TTO",
      region: "Americas",
      flagEmoji: "🇹🇹",
      dialCode: "+1868",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "TTD",
          name: "Trinidad and Tobago dollar",
          symbol: "\$",
        ),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Port_of_Spain"],
    ),
    Country(
      name: "Tunisia",
      iso2: "TN",
      iso3: "TUN",
      region: "Africa",
      flagEmoji: "🇹🇳",
      dialCode: "+216",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TND", name: "Tunisian dinar", symbol: "ت.د"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Africa/Tunis"],
    ),
    Country(
      name: "Turkey",
      iso2: "TR",
      iso3: "TUR",
      region: "Asia",
      flagEmoji: "🇹🇷",
      dialCode: "+90",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TRY", name: "Turkish lira", symbol: "₺"),
      ],
      languages: <String>["Turkish"],
      timezones: <String>["Europe/Istanbul"],
    ),
    Country(
      name: "Turkmenistan",
      iso2: "TM",
      iso3: "TKM",
      region: "Asia",
      flagEmoji: "🇹🇲",
      dialCode: "+993",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "TMT", name: "Turkmenistan manat", symbol: "T"),
      ],
      languages: <String>["Turkmen"],
      timezones: <String>["Asia/Ashgabat"],
    ),
    Country(
      name: "Turks And Caicos Islands",
      iso2: "TC",
      iso3: "TCA",
      region: "Americas",
      flagEmoji: "🇹🇨",
      dialCode: "+1649",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/Grand_Turk"],
    ),
    Country(
      name: "Tuvalu",
      iso2: "TV",
      iso3: "TUV",
      region: "Oceania",
      flagEmoji: "🇹🇻",
      dialCode: "+688",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "AUD", name: "Australian dollar", symbol: "\$"),
        CurrencyInfo(code: "TVD", name: "Tuvaluan Dollar", symbol: "\$"),
      ],
      languages: <String>["Tuvaluan", "English"],
      timezones: <String>["Pacific/Funafuti"],
    ),
    Country(
      name: "Uganda",
      iso2: "UG",
      iso3: "UGA",
      region: "Africa",
      flagEmoji: "🇺🇬",
      dialCode: "+256",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "UGX", name: "Ugandan shilling", symbol: "USh"),
      ],
      languages: <String>["English", "Swahili"],
      timezones: <String>["Africa/Kampala"],
    ),
    Country(
      name: "Ukraine",
      iso2: "UA",
      iso3: "UKR",
      region: "Europe",
      flagEmoji: "🇺🇦",
      dialCode: "+380",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "UAH", name: "Ukrainian hryvnia", symbol: "₴"),
      ],
      languages: <String>["Ukrainian"],
      timezones: <String>[
        "Europe/Kiev",
        "Europe/Simferopol",
        "Europe/Uzhgorod",
        "Europe/Zaporozhye",
      ],
    ),
    Country(
      name: "United Arab Emirates",
      iso2: "AE",
      iso3: "ARE",
      region: "Asia",
      flagEmoji: "🇦🇪",
      dialCode: "+971",
      currencies: <CurrencyInfo>[
        CurrencyInfo(
          code: "AED",
          name: "United Arab Emirates dirham",
          symbol: "إ.د",
        ),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Dubai"],
    ),
    Country(
      name: "United Kingdom",
      iso2: "GB",
      iso3: "GBR",
      region: "Europe",
      flagEmoji: "🇬🇧",
      dialCode: "+44",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "GBP", name: "British pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>["Europe/London"],
    ),
    Country(
      name: "United States",
      iso2: "US",
      iso3: "USA",
      region: "Americas",
      flagEmoji: "🇺🇸",
      dialCode: "+1",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>[
        "America/Adak",
        "America/Anchorage",
        "America/Boise",
        "America/Chicago",
        "America/Denver",
        "America/Detroit",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Juneau",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Los_Angeles",
        "America/Menominee",
        "America/Metlakatla",
        "America/New_York",
        "America/Nome",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Phoenix",
        "America/Sitka",
        "America/Yakutat",
        "Pacific/Honolulu",
      ],
    ),
    Country(
      name: "United States Minor Outlying Islands",
      iso2: "UM",
      iso3: "UMI",
      region: "Americas",
      flagEmoji: "🇺🇲",
      dialCode: "+1",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["Pacific/Midway", "Pacific/Wake"],
    ),
    Country(
      name: "Uruguay",
      iso2: "UY",
      iso3: "URY",
      region: "Americas",
      flagEmoji: "🇺🇾",
      dialCode: "+598",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "UYU", name: "Uruguayan peso", symbol: "\$"),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Montevideo"],
    ),
    Country(
      name: "Uzbekistan",
      iso2: "UZ",
      iso3: "UZB",
      region: "Asia",
      flagEmoji: "🇺🇿",
      dialCode: "+998",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "UZS", name: "Uzbekistani soʻm", symbol: "лв"),
      ],
      languages: <String>["Uzbek"],
      timezones: <String>["Asia/Samarkand", "Asia/Tashkent"],
    ),
    Country(
      name: "Vanuatu",
      iso2: "VU",
      iso3: "VUT",
      region: "Oceania",
      flagEmoji: "🇻🇺",
      dialCode: "+678",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "VUV", name: "Vanuatu vatu", symbol: "VT"),
      ],
      languages: <String>["Bislama", "English", "French"],
      timezones: <String>["Pacific/Efate"],
    ),
    Country(
      name: "Vatican City State (Holy See)",
      iso2: "VA",
      iso3: "VAT",
      region: "Europe",
      flagEmoji: "🇻🇦",
      dialCode: "+379",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
      ],
      languages: <String>["Italian"],
      timezones: <String>["Europe/Vatican"],
    ),
    Country(
      name: "Venezuela",
      iso2: "VE",
      iso3: "VEN",
      region: "Americas",
      flagEmoji: "🇻🇪",
      dialCode: "+58",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "VEF", name: "Bolívar", symbol: "Bs"),
        CurrencyInfo(code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.S."),
        CurrencyInfo(code: "VED", name: "", symbol: ""),
      ],
      languages: <String>["Spanish"],
      timezones: <String>["America/Caracas"],
    ),
    Country(
      name: "Vietnam",
      iso2: "VN",
      iso3: "VNM",
      region: "Asia",
      flagEmoji: "🇻🇳",
      dialCode: "+84",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "VND", name: "Vietnamese đồng", symbol: "₫"),
      ],
      languages: <String>["Vietnamese"],
      timezones: <String>["Asia/Ho_Chi_Minh"],
    ),
    Country(
      name: "Virgin Islands (British)",
      iso2: "VG",
      iso3: "VGB",
      region: "Americas",
      flagEmoji: "🇻🇬",
      dialCode: "+1284",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>[],
      timezones: <String>["America/Tortola"],
    ),
    Country(
      name: "Virgin Islands (US)",
      iso2: "VI",
      iso3: "VIR",
      region: "Americas",
      flagEmoji: "🇻🇮",
      dialCode: "+1340",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "USD", name: "United States dollar", symbol: "\$"),
      ],
      languages: <String>["English"],
      timezones: <String>["America/St_Thomas"],
    ),
    Country(
      name: "Wallis And Futuna Islands",
      iso2: "WF",
      iso3: "WLF",
      region: "Oceania",
      flagEmoji: "🇼🇫",
      dialCode: "+681",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "XPF", name: "CFP franc", symbol: "₣"),
      ],
      languages: <String>["French"],
      timezones: <String>["Pacific/Wallis"],
    ),
    Country(
      name: "Western Sahara",
      iso2: "EH",
      iso3: "ESH",
      region: "Africa",
      flagEmoji: "🇪🇭",
      dialCode: "+212",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "MAD", name: "Moroccan Dirham", symbol: "MAD"),
      ],
      languages: <String>["Arabic", "Berber"],
      timezones: <String>["Africa/El_Aaiun"],
    ),
    Country(
      name: "Yemen",
      iso2: "YE",
      iso3: "YEM",
      region: "Asia",
      flagEmoji: "🇾🇪",
      dialCode: "+967",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "YER", name: "Yemeni rial", symbol: "﷼"),
      ],
      languages: <String>["Arabic"],
      timezones: <String>["Asia/Aden"],
    ),
    Country(
      name: "Zambia",
      iso2: "ZM",
      iso3: "ZMB",
      region: "Africa",
      flagEmoji: "🇿🇲",
      dialCode: "+260",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ZMW", name: "Zambian kwacha", symbol: "ZK"),
      ],
      languages: <String>["English"],
      timezones: <String>["Africa/Lusaka"],
    ),
    Country(
      name: "Zimbabwe",
      iso2: "ZW",
      iso3: "ZWE",
      region: "Africa",
      flagEmoji: "🇿🇼",
      dialCode: "+263",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "ZWL", name: "Zimbabwe Dollar", symbol: "\$"),
        CurrencyInfo(code: "USD", name: "", symbol: ""),
      ],
      languages: <String>["English", "Shona", "Sindebele"],
      timezones: <String>["Africa/Harare"],
    ),
    Country(
      name: "Ascension Island",
      iso2: "AC",
      iso3: "",
      region: "Africa",
      flagEmoji: "🇦🇨",
      dialCode: "+247",
      currencies: <CurrencyInfo>[
        CurrencyInfo(code: "SHP", name: "Saint Helena Pound", symbol: "£"),
      ],
      languages: <String>["English"],
      timezones: <String>[],
    ),
    Country(
      name: "Netherlands Antilles",
      iso2: "AN",
      iso3: "",
      region: "",
      flagEmoji: "🇧🇶",
      dialCode: "",
      currencies: <CurrencyInfo>[],
      languages: <String>[],
      timezones: <String>[],
    ),
  ];
}
