import 'package:flutter/material.dart';
import '../my_color_scheme.dart';

@immutable
class MyPurpleColorScheme extends MyColorScheme {
  const MyPurpleColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyPurpleColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff030712),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff030712),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff030712),
    super.primary = const Color(0xff9333ea),
    super.primaryForeground = const Color(0xfffaf5ff),
    super.secondary = const Color(0xfff3f4f6),
    super.secondaryForeground = const Color(0xff111827),
    super.muted = const Color(0xfff3f4f6),
    super.mutedForeground = const Color(0xff6b7280),
    super.accent = const Color(0xfff3f4f6),
    super.accentForeground = const Color(0xff111827),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfff9fafb),
    super.border = const Color(0xffe5e7eb),
    super.input = const Color(0xffe5e7eb),
    super.ring = const Color(0xff9333ea),
    super.selection = const Color(0xFFB4D7FF),
    super.chart1 = const Color(0xFFE76E4F),
    super.chart2 = const Color(0xFF299D8F),
    super.chart3 = const Color(0xFF264753),
    super.chart4 = const Color(0xFFE8C468),
    super.chart5 = const Color(0xFFF4A361),
  });

  const MyPurpleColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff030712),
    super.foreground = const Color(0xfff9fafb),
    super.card = const Color(0xff030712),
    super.cardForeground = const Color(0xfff9fafb),
    super.popover = const Color(0xff030712),
    super.popoverForeground = const Color(0xfff9fafb),
    super.primary = const Color(0xff7e22ce),
    super.primaryForeground = const Color(0xfffaf5ff),
    super.secondary = const Color(0xff1f2937),
    super.secondaryForeground = const Color(0xfff9fafb),
    super.muted = const Color(0xff1f2937),
    super.mutedForeground = const Color(0xff9ca3af),
    super.accent = const Color(0xff1f2937),
    super.accentForeground = const Color(0xfff9fafb),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfff9fafb),
    super.border = const Color(0xff1f2937),
    super.input = const Color(0xff1f2937),
    super.ring = const Color(0xff7e22ce),
    super.selection = const Color(0xFF355172),
    super.chart1 = const Color(0xFF2661D8),
    super.chart2 = const Color(0xFF2DB789),
    super.chart3 = const Color(0xFFE88C30),
    super.chart4 = const Color(0xFFAF56DB),
    super.chart5 = const Color(0xFFE2366F),
  });
}
