import 'dart:io';

const _entrypoints = <String>[
  'lib/common_tools.dart',
  'lib/theme.dart',
  'lib/layout.dart',
  'lib/components.dart',
  'lib/components/actions.dart',
  'lib/components/forms.dart',
  'lib/components/feedback.dart',
  'lib/components/data_display.dart',
  'lib/components/navigation.dart',
  'lib/components/media.dart',
  'lib/network.dart',
  'lib/services.dart',
  'lib/utilities.dart',
  'lib/extensions/context.dart',
  'lib/extensions/string.dart',
  'lib/extensions/iterable.dart',
  'lib/extensions/date.dart',
  'lib/extensions/number.dart',
  'lib/extensions/map.dart',
  'lib/extensions/widget.dart',
  'lib/extensions/duration.dart',
  'lib/localization.dart',
  'lib/files.dart',
];

final _exportPattern = RegExp(
  r'''export\s+['"]([^'"]+)['"](?:\s+(show|hide)\s+([^;]+))?\s*;''',
);
final _declarationPattern = RegExp(
  r'^(?:abstract\s+|base\s+|final\s+|interface\s+|sealed\s+)*'
  r'(class|enum|mixin|extension\s+type|extension|typedef)\s+'
  r'([A-Za-z]\w*)',
  multiLine: true,
);

void main(List<String> arguments) {
  final root = Directory.current;
  final inventoryFile = File('tool/public_api.txt');
  final symbols = <String>{};

  for (final entrypoint in _entrypoints) {
    final file = File(entrypoint);
    if (!file.existsSync()) {
      stderr.writeln('Missing public entrypoint: $entrypoint');
      exitCode = 2;
      return;
    }
    _collect(file, root, symbols, <String>{});
  }

  final output = <String>[
    '# Generated by `dart run tool/public_api.dart`.',
    '# Review changes to this file as public API changes.',
    ...symbols.toList()..sort(),
    '',
  ].join('\n');

  if (arguments.contains('--check')) {
    if (!inventoryFile.existsSync() ||
        inventoryFile.readAsStringSync() != output) {
      stderr.writeln(
        'Public API inventory changed. Run '
        '`dart run tool/public_api.dart` and review the diff.',
      );
      exitCode = 1;
    }
    return;
  }

  inventoryFile.writeAsStringSync(output);
}

void _collect(
  File file,
  Directory root,
  Set<String> symbols,
  Set<String> visited,
) {
  final normalized = file.absolute.path.replaceAll(r'\', '/');
  if (!visited.add(normalized)) return;

  final source = file.readAsStringSync();
  final relativePath = file.absolute.path
      .substring(root.absolute.path.length + 1)
      .replaceAll(r'\', '/');

  for (final match in _declarationPattern.allMatches(source)) {
    final name = match.group(2)!;
    if (!name.startsWith('_')) symbols.add('$name\t$relativePath');
  }

  for (final match in _exportPattern.allMatches(source)) {
    final exportedPath = match.group(1)!;
    if (exportedPath.startsWith('dart:') ||
        exportedPath.startsWith('package:')) {
      continue;
    }

    final exportedFile = File.fromUri(file.uri.resolve(exportedPath));
    if (!exportedFile.existsSync()) continue;

    final before = Set<String>.of(symbols);
    _collect(exportedFile, root, symbols, visited);

    final mode = match.group(2);
    final names = match
        .group(3)
        ?.split(',')
        .map((name) => name.trim())
        .where((name) => name.isNotEmpty)
        .toSet();
    if (mode == null || names == null) continue;

    final added = symbols.difference(before);
    if (mode == 'show') {
      symbols.removeAll(added.where((line) => !names.contains(_nameOf(line))));
    } else {
      symbols.removeAll(added.where((line) => names.contains(_nameOf(line))));
    }
  }
}

String _nameOf(String inventoryLine) => inventoryLine.split('\t').first;
