import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyBrownColorScheme extends MyColorScheme {
  const MyBrownColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyBrownColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xff983127),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xfff5f5f4),
    super.secondaryForeground = const Color(0xff1c1917),
    super.muted = const Color(0xfff5f5f4),
    super.mutedForeground = const Color(0xff79716b),
    super.accent = const Color(0xfff5f5f4),
    super.accentForeground = const Color(0xff1c1917),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe7e5e4),
    super.input = const Color(0xffe7e5e4),
    super.ring = const Color(0xff983127),
    super.selection = const Color(0x47983127),
    super.chart1 = const Color(0xff983127),
    super.chart2 = const Color(0xff746738),
    super.chart3 = const Color(0xff000000),
    super.chart4 = const Color(0xffc8675d),
    super.chart5 = const Color(0xffb0a06c),
  });

  const MyBrownColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffafaf9),
    super.card = const Color(0xff1c1917),
    super.cardForeground = const Color(0xfffafaf9),
    super.popover = const Color(0xff1c1917),
    super.popoverForeground = const Color(0xfffafaf9),
    super.primary = const Color(0xff983127),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xff292524),
    super.secondaryForeground = const Color(0xfffafaf9),
    super.muted = const Color(0xff292524),
    super.mutedForeground = const Color(0xffa6a09b),
    super.accent = const Color(0xff292524),
    super.accentForeground = const Color(0xfffafaf9),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xffc8675d),
    super.selection = const Color(0x47983127),
    super.chart1 = const Color(0xffc8675d),
    super.chart2 = const Color(0xffb0a06c),
    super.chart3 = const Color(0xfffafaf9),
    super.chart4 = const Color(0xff983127),
    super.chart5 = const Color(0xffd2c59b),
  });
}
