import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyMauveColorScheme extends MyColorScheme {
  const MyMauveColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyMauveColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c090c),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c090c),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c090c),
    super.primary = const Color(0xff1d161e),
    super.primaryForeground = const Color(0xfffafafa),
    super.secondary = const Color(0xfff3f1f3),
    super.secondaryForeground = const Color(0xff1d161e),
    super.muted = const Color(0xfff3f1f3),
    super.mutedForeground = const Color(0xff79697b),
    super.accent = const Color(0xfff3f1f3),
    super.accentForeground = const Color(0xff1d161e),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe7e4e7),
    super.input = const Color(0xffe7e4e7),
    super.ring = const Color(0xffa89ea9),
    super.selection = const Color(0x471d161e),
    super.chart1 = const Color(0xffd7d0d7),
    super.chart2 = const Color(0xff79697b),
    super.chart3 = const Color(0xff594c5b),
    super.chart4 = const Color(0xff463947),
    super.chart5 = const Color(0xff2a212c),
  });

  const MyMauveColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff0c090c),
    super.foreground = const Color(0xfffafafa),
    super.card = const Color(0xff1d161e),
    super.cardForeground = const Color(0xfffafafa),
    super.popover = const Color(0xff1d161e),
    super.popoverForeground = const Color(0xfffafafa),
    super.primary = const Color(0xffe7e4e7),
    super.primaryForeground = const Color(0xff1d161e),
    super.secondary = const Color(0xff2a212c),
    super.secondaryForeground = const Color(0xfffafafa),
    super.muted = const Color(0xff2a212c),
    super.mutedForeground = const Color(0xffa89ea9),
    super.accent = const Color(0xff2a212c),
    super.accentForeground = const Color(0xfffafafa),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff79697b),
    super.selection = const Color(0x47e7e4e7),
    super.chart1 = const Color(0xffd7d0d7),
    super.chart2 = const Color(0xff79697b),
    super.chart3 = const Color(0xff594c5b),
    super.chart4 = const Color(0xff463947),
    super.chart5 = const Color(0xff2a212c),
  });
}
