import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyMistColorScheme extends MyColorScheme {
  const MyMistColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyMistColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff090b0c),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff090b0c),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff090b0c),
    super.primary = const Color(0xff161b1d),
    super.primaryForeground = const Color(0xfff9fbfb),
    super.secondary = const Color(0xfff1f3f3),
    super.secondaryForeground = const Color(0xff161b1d),
    super.muted = const Color(0xfff1f3f3),
    super.mutedForeground = const Color(0xff67787c),
    super.accent = const Color(0xfff1f3f3),
    super.accentForeground = const Color(0xff161b1d),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe3e7e8),
    super.input = const Color(0xffe3e7e8),
    super.ring = const Color(0xff9ca8ab),
    super.selection = const Color(0x47161b1d),
    super.chart1 = const Color(0xffd0d6d8),
    super.chart2 = const Color(0xff67787c),
    super.chart3 = const Color(0xff4b585b),
    super.chart4 = const Color(0xff394447),
    super.chart5 = const Color(0xff22292b),
  });

  const MyMistColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff090b0c),
    super.foreground = const Color(0xfff9fbfb),
    super.card = const Color(0xff161b1d),
    super.cardForeground = const Color(0xfff9fbfb),
    super.popover = const Color(0xff161b1d),
    super.popoverForeground = const Color(0xfff9fbfb),
    super.primary = const Color(0xffe3e7e8),
    super.primaryForeground = const Color(0xff161b1d),
    super.secondary = const Color(0xff22292b),
    super.secondaryForeground = const Color(0xfff9fbfb),
    super.muted = const Color(0xff22292b),
    super.mutedForeground = const Color(0xff9ca8ab),
    super.accent = const Color(0xff22292b),
    super.accentForeground = const Color(0xfff9fbfb),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff67787c),
    super.selection = const Color(0x47e3e7e8),
    super.chart1 = const Color(0xffd0d6d8),
    super.chart2 = const Color(0xff67787c),
    super.chart3 = const Color(0xff4b585b),
    super.chart4 = const Color(0xff394447),
    super.chart5 = const Color(0xff22292b),
  });
}
