import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MySkyColorScheme extends MyColorScheme {
  const MySkyColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MySkyColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0a0a0a),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0a0a0a),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0a0a0a),
    super.primary = const Color(0xff0069a8),
    super.primaryForeground = const Color(0xfff0f9ff),
    super.secondary = const Color(0xfff4f4f5),
    super.secondaryForeground = const Color(0xff18181b),
    super.muted = const Color(0xfff5f5f5),
    super.mutedForeground = const Color(0xff737373),
    super.accent = const Color(0xfff5f5f5),
    super.accentForeground = const Color(0xff171717),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe5e5e5),
    super.input = const Color(0xffe5e5e5),
    super.ring = const Color(0xffa1a1a1),
    super.selection = const Color(0x470069a8),
    super.chart1 = const Color(0xff74d4ff),
    super.chart2 = const Color(0xff00a6f4),
    super.chart3 = const Color(0xff0084d1),
    super.chart4 = const Color(0xff0069a8),
    super.chart5 = const Color(0xff00598a),
  });

  const MySkyColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff0a0a0a),
    super.foreground = const Color(0xfffafafa),
    super.card = const Color(0xff171717),
    super.cardForeground = const Color(0xfffafafa),
    super.popover = const Color(0xff171717),
    super.popoverForeground = const Color(0xfffafafa),
    super.primary = const Color(0xff00598a),
    super.primaryForeground = const Color(0xfff0f9ff),
    super.secondary = const Color(0xff27272a),
    super.secondaryForeground = const Color(0xfffafafa),
    super.muted = const Color(0xff262626),
    super.mutedForeground = const Color(0xffa1a1a1),
    super.accent = const Color(0xff262626),
    super.accentForeground = const Color(0xfffafafa),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff737373),
    super.selection = const Color(0x4700598a),
    super.chart1 = const Color(0xff74d4ff),
    super.chart2 = const Color(0xff00a6f4),
    super.chart3 = const Color(0xff0084d1),
    super.chart4 = const Color(0xff0069a8),
    super.chart5 = const Color(0xff00598a),
  });
}
