import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MySlateColorScheme extends MyColorScheme {
  const MySlateColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MySlateColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff020618),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff020618),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff020618),
    super.primary = const Color(0xff0f172b),
    super.primaryForeground = const Color(0xfff8fafc),
    super.secondary = const Color(0xfff1f5f9),
    super.secondaryForeground = const Color(0xff0f172b),
    super.muted = const Color(0xfff1f5f9),
    super.mutedForeground = const Color(0xff62748e),
    super.accent = const Color(0xfff1f5f9),
    super.accentForeground = const Color(0xff0f172b),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe2e8f0),
    super.input = const Color(0xffe2e8f0),
    super.ring = const Color(0xff90a1b9),
    super.selection = const Color(0x470f172b),
    super.chart1 = const Color(0xfff54900),
    super.chart2 = const Color(0xff009689),
    super.chart3 = const Color(0xff104e64),
    super.chart4 = const Color(0xffffb900),
    super.chart5 = const Color(0xfffe9a00),
  });

  const MySlateColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff020618),
    super.foreground = const Color(0xfff8fafc),
    super.card = const Color(0xff0f172b),
    super.cardForeground = const Color(0xfff8fafc),
    super.popover = const Color(0xff0f172b),
    super.popoverForeground = const Color(0xfff8fafc),
    super.primary = const Color(0xffe2e8f0),
    super.primaryForeground = const Color(0xff0f172b),
    super.secondary = const Color(0xff1d293d),
    super.secondaryForeground = const Color(0xfff8fafc),
    super.muted = const Color(0xff1d293d),
    super.mutedForeground = const Color(0xff90a1b9),
    super.accent = const Color(0xff1d293d),
    super.accentForeground = const Color(0xfff8fafc),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff6a7282),
    super.selection = const Color(0x47e2e8f0),
    super.chart1 = const Color(0xff1447e6),
    super.chart2 = const Color(0xff00bc7d),
    super.chart3 = const Color(0xfffe9a00),
    super.chart4 = const Color(0xffad46ff),
    super.chart5 = const Color(0xffff2056),
  });
}
