import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyStoneColorScheme extends MyColorScheme {
  const MyStoneColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyStoneColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xff1c1917),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xfff5f5f4),
    super.secondaryForeground = const Color(0xff1c1917),
    super.muted = const Color(0xfff5f5f4),
    super.mutedForeground = const Color(0xff78716c),
    super.accent = const Color(0xfff5f5f4),
    super.accentForeground = const Color(0xff1c1917),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafaf9),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe7e5e4),
    super.input = const Color(0xffe7e5e4),
    super.ring = const Color(0xff0c0a09),
    super.selection = const Color(0xFFB4D7FF),
    super.chart1 = const Color(0xFFE76E4F),
    super.chart2 = const Color(0xFF299D8F),
    super.chart3 = const Color(0xFF264753),
    super.chart4 = const Color(0xFFE8C468),
    super.chart5 = const Color(0xFFF4A361),
  });

  const MyStoneColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffafaf9),
    super.card = const Color(0xff0c0a09),
    super.cardForeground = const Color(0xfffafaf9),
    super.popover = const Color(0xff0c0a09),
    super.popoverForeground = const Color(0xfffafaf9),
    super.primary = const Color(0xfffafaf9),
    super.primaryForeground = const Color(0xff1c1917),
    super.secondary = const Color(0xff292524),
    super.secondaryForeground = const Color(0xfffafaf9),
    super.muted = const Color(0xff292524),
    super.mutedForeground = const Color(0xffa8a29e),
    super.accent = const Color(0xff292524),
    super.accentForeground = const Color(0xfffafaf9),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafaf9),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0xff292524),
    super.input = const Color(0xff292524),
    super.ring = const Color(0xffd6d3d1),
    super.selection = const Color(0xFF355172),
    super.chart1 = const Color(0xFF2661D8),
    super.chart2 = const Color(0xFF2DB789),
    super.chart3 = const Color(0xFFE88C30),
    super.chart4 = const Color(0xFFAF56DB),
    super.chart5 = const Color(0xFFE2366F),
  });
}
