import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyTaupeColorScheme extends MyColorScheme {
  const MyTaupeColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyTaupeColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xff1d1816),
    super.primaryForeground = const Color(0xfffbfaf9),
    super.secondary = const Color(0xfff3f1f1),
    super.secondaryForeground = const Color(0xff1d1816),
    super.muted = const Color(0xfff3f1f1),
    super.mutedForeground = const Color(0xff7c6d67),
    super.accent = const Color(0xfff3f1f1),
    super.accentForeground = const Color(0xff1d1816),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xffffffff),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe8e4e3),
    super.input = const Color(0xffe8e4e3),
    super.ring = const Color(0xffaba09c),
    super.selection = const Color(0x471d1816),
    super.chart1 = const Color(0xffd8d2d0),
    super.chart2 = const Color(0xff7c6d67),
    super.chart3 = const Color(0xff5b4f4b),
    super.chart4 = const Color(0xff473c39),
    super.chart5 = const Color(0xff2b2422),
  });

  const MyTaupeColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffbfaf9),
    super.card = const Color(0xff1d1816),
    super.cardForeground = const Color(0xfffbfaf9),
    super.popover = const Color(0xff1d1816),
    super.popoverForeground = const Color(0xfffbfaf9),
    super.primary = const Color(0xffe8e4e3),
    super.primaryForeground = const Color(0xff1d1816),
    super.secondary = const Color(0xff2b2422),
    super.secondaryForeground = const Color(0xfffbfaf9),
    super.muted = const Color(0xff2b2422),
    super.mutedForeground = const Color(0xffaba09c),
    super.accent = const Color(0xff2b2422),
    super.accentForeground = const Color(0xfffbfaf9),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff000000),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff7c6d67),
    super.selection = const Color(0x47e8e4e3),
    super.chart1 = const Color(0xffd8d2d0),
    super.chart2 = const Color(0xff7c6d67),
    super.chart3 = const Color(0xff5b4f4b),
    super.chart4 = const Color(0xff473c39),
    super.chart5 = const Color(0xff2b2422),
  });
}
