import 'package:flutter/material.dart';
import '../my_color_scheme.dart';
import 'status_colors.dart';

@immutable
class MyZincColorScheme extends MyColorScheme {
  const MyZincColorScheme({
    required super.brightness,
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.warning,
    required super.warningForeground,
    required super.success,
    required super.successForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.chart1,
    required super.chart2,
    required super.chart3,
    required super.chart4,
    required super.chart5,
  });

  const MyZincColorScheme.light({
    super.brightness = Brightness.light,
    super.background = const Color(0xFFFFFFFF),
    super.foreground = const Color(0xff09090b),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff09090b),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff09090b),
    super.primary = const Color(0xff18181b),
    super.primaryForeground = const Color(0xfffafafa),
    super.secondary = const Color(0xfff4f4f5),
    super.secondaryForeground = const Color(0xff18181b),
    super.muted = const Color(0xfff4f4f5),
    super.mutedForeground = const Color(0xff71717a),
    super.accent = const Color(0xfff4f4f5),
    super.accentForeground = const Color(0xff18181b),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafafa),
    super.warning = MyStatusColorDefaults.warningLight,
    super.warningForeground = MyStatusColorDefaults.warningForegroundLight,
    super.success = MyStatusColorDefaults.successLight,
    super.successForeground = MyStatusColorDefaults.successForegroundLight,
    super.border = const Color(0xffe4e4e7),
    super.input = const Color(0xffe4e4e7),
    super.ring = const Color(0xff18181b),
    super.selection = const Color(0xFFB4D7FF),
    super.chart1 = const Color(0xFFE76E4F),
    super.chart2 = const Color(0xFF299D8F),
    super.chart3 = const Color(0xFF264753),
    super.chart4 = const Color(0xFFE8C468),
    super.chart5 = const Color(0xFFF4A361),
  });

  const MyZincColorScheme.dark({
    super.brightness = Brightness.dark,
    super.background = const Color(0xff09090b),
    super.foreground = const Color(0xfffafafa),
    super.card = const Color(0xff09090b),
    super.cardForeground = const Color(0xfffafafa),
    super.popover = const Color(0xff09090b),
    super.popoverForeground = const Color(0xfffafafa),
    super.primary = const Color(0xfffafafa),
    super.primaryForeground = const Color(0xff18181b),
    super.secondary = const Color(0xff27272a),
    super.secondaryForeground = const Color(0xfffafafa),
    super.muted = const Color(0xff27272a),
    super.mutedForeground = const Color(0xffa1a1aa),
    super.accent = const Color(0xff27272a),
    super.accentForeground = const Color(0xfffafafa),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafafa),
    super.warning = MyStatusColorDefaults.warningDark,
    super.warningForeground = MyStatusColorDefaults.warningForegroundDark,
    super.success = MyStatusColorDefaults.successDark,
    super.successForeground = MyStatusColorDefaults.successForegroundDark,
    super.border = const Color(0xff27272a),
    super.input = const Color(0xff27272a),
    super.ring = const Color(0xffd4d4d8),
    super.selection = const Color(0xFF355172),
    super.chart1 = const Color(0xFF2661D8),
    super.chart2 = const Color(0xFF2DB789),
    super.chart3 = const Color(0xFFE88C30),
    super.chart4 = const Color(0xFFAF56DB),
    super.chart5 = const Color(0xFFE2366F),
  });
}
